import { z } from "zod";
import { COMMAND_PATHS, type CommandPath } from "../../utils/command-catalog.js";
import {
  errorEnvelopeSchema,
  nextActionSchema,
  successEnvelopeSchema,
} from "./common.js";

const nullableString = z.string().nullable();
const optionalString = z.string().optional();
const optionalNullableString = nullableString.optional();
const optionalBoolean = z.boolean().optional();
const optionalNumber = z.number().optional();
const optionalUnknown = z.unknown().optional();
const unknownArray = z.array(z.unknown());
const unknownRecord = z.record(z.unknown());
const optionalNextActions = z.array(nextActionSchema).optional();

const warningSchema = z.object({
  code: z.string().optional(),
  category: z.string().optional(),
  message: z.string(),
});

const deprecationWarningSchema = z.object({
  code: z.string(),
  message: z.string(),
  replacementCommand: z.string(),
});

const externalGuidanceSchema = z.object({
  kind: z.string(),
  message: z.string(),
  command: z.string().optional(),
});

const rawUnsignedTransactionSchema = z.object({
  from: optionalString,
  to: optionalString,
  data: optionalString,
  value: optionalString,
  valueHex: optionalString,
  chainId: optionalNumber,
  description: optionalString,
});

const poolBaseSchema = z.object({
  chain: optionalString,
  asset: z.string(),
  tokenAddress: z.string(),
  pool: z.string(),
  scope: z.string(),
  decimals: z.number(),
  minimumDeposit: z.string(),
  vettingFeeBPS: z.string(),
  maxRelayFeeBPS: z.string(),
  totalInPoolValue: nullableString,
  totalInPoolValueUsd: optionalNullableString,
  totalDepositsValue: optionalNullableString,
  totalDepositsValueUsd: optionalNullableString,
  acceptedDepositsValue: optionalNullableString,
  acceptedDepositsValueUsd: optionalNullableString,
  pendingDepositsValue: optionalNullableString,
  pendingDepositsValueUsd: optionalNullableString,
  totalDepositsCount: z.number().nullable(),
  acceptedDepositsCount: z.number().nullable().optional(),
  pendingDepositsCount: z.number().nullable(),
  growth24h: z.number().nullable().optional(),
  pendingGrowth24h: z.number().nullable().optional(),
  myPoolAccountsCount: optionalNumber,
});

const timeBasedStatsSchema = z.object({
  tvl: z.string().nullable().optional(),
  tvlUsd: z.string().nullable().optional(),
  avgDepositSizeUsd: z.string().nullable().optional(),
  totalDepositsCount: z.number().nullable().optional(),
  totalWithdrawalsCount: z.number().nullable().optional(),
  totalDepositsValue: z.string().nullable().optional(),
  totalWithdrawalsValue: z.string().nullable().optional(),
  totalDepositsValueUsd: z.string().nullable().optional(),
  totalWithdrawalsValueUsd: z.string().nullable().optional(),
});

const transactionResultBaseSchema = z.object({
  operation: z.string(),
  status: z.enum(["submitted", "confirmed"]).optional(),
  submissionId: optionalString,
  txHash: optionalString,
  amount: z.string(),
  asset: z.string(),
  chain: z.string(),
  poolAccountNumber: optionalNumber,
  poolAccountId: optionalString,
  poolAddress: optionalString,
  scope: optionalString,
  blockNumber: z.union([z.string(), z.number()]).nullable().optional(),
  explorerUrl: z.string().nullable().optional(),
  reconciliationRequired: optionalBoolean,
  localStateSynced: optionalBoolean,
  warningCode: z.string().nullable().optional(),
  warnings: z.array(warningSchema).optional(),
  deprecationWarning: deprecationWarningSchema.optional(),
  nextActions: optionalNextActions,
});

const dryRunBaseSchema = z.object({
  operation: optionalString,
  mode: optionalString,
  dryRun: z.boolean().optional(),
  chain: optionalString,
  asset: optionalString,
  amount: optionalString,
  warnings: z.array(warningSchema).optional(),
  nextActions: optionalNextActions,
});

const unsignedBaseSchema = z.object({
  mode: optionalString,
  operation: optionalString,
  chain: optionalString,
  transactions: z.array(rawUnsignedTransactionSchema).optional(),
  warnings: z.array(warningSchema).optional(),
  nextActions: optionalNextActions,
});

const configSchema = z.object({
  mode: optionalString,
  operation: optionalString,
  profile: optionalString,
  activeProfile: optionalNullableString,
  configDir: optionalString,
  configPath: optionalString,
  key: optionalString,
  value: optionalUnknown,
  previousValue: optionalUnknown,
  defaultChain: optionalNullableString,
  profiles: unknownArray.optional(),
  settings: unknownRecord.optional(),
  updated: optionalBoolean,
  nextActions: optionalNextActions,
});

const flowSchema = z.object({
  mode: optionalString,
  action: optionalString,
  dryRun: optionalBoolean,
  workflowId: optionalString,
  workflowKind: optionalString,
  phase: optionalString,
  walletMode: optionalString,
  walletAddress: z.string().nullable().optional(),
  requiredNativeFunding: z.string().nullable().optional(),
  requiredTokenFunding: z.string().nullable().optional(),
  backupConfirmed: optionalBoolean,
  chain: optionalString,
  asset: optionalString,
  depositAmount: optionalString,
  recipient: z.string().nullable().optional(),
  poolAccountId: z.string().nullable().optional(),
  poolAccountNumber: optionalNumber,
  depositTxHash: z.string().nullable().optional(),
  depositBlockNumber: z.string().nullable().optional(),
  depositExplorerUrl: z.string().nullable().optional(),
  committedValue: z.string().nullable().optional(),
  aspStatus: optionalString,
  withdrawalTxHash: z.string().nullable().optional(),
  withdrawalBlockNumber: z.string().nullable().optional(),
  withdrawalExplorerUrl: z.string().nullable().optional(),
  ragequitTxHash: z.string().nullable().optional(),
  ragequitBlockNumber: z.string().nullable().optional(),
  ragequitExplorerUrl: z.string().nullable().optional(),
  privacyDelayProfile: optionalString,
  privacyDelayConfigured: optionalUnknown,
  privacyDelayRandom: optionalBoolean,
  privacyDelayRangeSeconds: z.array(z.number()).optional(),
  privacyDelayUntil: z.string().nullable().optional(),
  nextPollAfter: z.string().nullable().optional(),
  vettingFee: optionalUnknown,
  vettingFeeBPS: optionalString,
  vettingFeeAmount: optionalString,
  estimatedCommitted: optionalString,
  estimatedCommittedValue: optionalString,
  feesApply: optionalBoolean,
  warnings: z.array(z.record(z.unknown())).optional(),
  nextActions: optionalNextActions,
});

const accountSchema = z.object({
  poolAccountNumber: optionalNumber,
  poolAccountId: optionalString,
  status: optionalString,
  aspStatus: optionalString,
  asset: optionalString,
  scope: optionalString,
  value: optionalString,
  hash: optionalString,
  label: optionalString,
  blockNumber: optionalString,
  txHash: optionalString,
  explorerUrl: optionalString,
  chain: optionalString,
  chainId: optionalNumber,
});

const balanceSchema = z.object({
  asset: optionalString,
  balance: optionalString,
  usdValue: optionalString,
  poolAccounts: optionalNumber,
  chain: optionalString,
  chainId: optionalNumber,
});

const accountsSchema = z.object({
  chain: z.string(),
  requestedChain: z.string().nullable().optional(),
  allChains: optionalBoolean,
  chains: z.array(z.string()).optional(),
  warnings: z.array(warningSchema).optional(),
  lastSyncTime: optionalNullableString,
  syncSkipped: optionalBoolean,
  accounts: z.array(accountSchema).optional(),
  balances: z.array(balanceSchema).optional(),
  pendingCount: optionalNumber,
  approvedCount: optionalNumber,
  poaRequiredCount: optionalNumber,
  declinedCount: optionalNumber,
  unknownCount: optionalNumber,
  spentCount: optionalNumber,
  exitedCount: optionalNumber,
  nextActions: optionalNextActions,
});

const activityEventSchema = z.object({
  type: optionalString,
  txHash: optionalString,
  explorerUrl: optionalString,
  reviewStatus: optionalString,
  amountRaw: optionalString,
  amountFormatted: optionalString,
  poolSymbol: optionalString,
  poolAddress: optionalString,
  chainId: optionalNumber,
  timestamp: z.union([z.string(), z.number()]).optional(),
});

const activitySchema = z.object({
  mode: optionalString,
  chain: z.string(),
  chains: z.array(z.string()).optional(),
  page: optionalNumber,
  perPage: optionalNumber,
  total: z.number().nullable().optional(),
  totalEvents: z.number().nullable().optional(),
  totalPages: z.number().nullable().optional(),
  chainFiltered: optionalBoolean,
  note: optionalString,
  asset: optionalString,
  pool: optionalString,
  scope: optionalString,
  events: z.array(activityEventSchema),
  nextActions: optionalNextActions,
});

const statsSchema = z.object({
  mode: optionalString,
  command: optionalString,
  invokedAs: optionalString,
  deprecationWarning: deprecationWarningSchema.optional(),
  chain: z.string(),
  chains: z.array(z.string()).optional(),
  asset: optionalString,
  pool: optionalString,
  scope: optionalString,
  cacheTimestamp: optionalNullableString,
  allTime: timeBasedStatsSchema.nullable().optional(),
  last24h: timeBasedStatsSchema.nullable().optional(),
  perChain: z.array(z.object({
    chain: z.string(),
    cacheTimestamp: optionalNullableString,
    allTime: timeBasedStatsSchema.nullable(),
    last24h: timeBasedStatsSchema.nullable(),
  })).optional(),
  nextActions: optionalNextActions,
});

const recipientSchema = z.object({
  address: optionalString,
  ensName: z.string().nullable().optional(),
  label: z.string().nullable().optional(),
  chain: z.string().nullable().optional(),
  source: optionalString,
  useCount: optionalNumber,
  lastUsedAt: z.string().nullable().optional(),
});

const recipientsSchema = z.object({
  mode: optionalString,
  operation: optionalString,
  chain: z.string().nullable().optional(),
  allChains: optionalBoolean,
  recipients: z.array(recipientSchema).optional(),
  recipient: recipientSchema.optional(),
  removed: optionalBoolean,
  cleared: optionalBoolean,
  count: optionalNumber,
  warnings: z.array(warningSchema).optional(),
  deprecationWarning: deprecationWarningSchema.optional(),
  nextActions: optionalNextActions,
});

const migrateStatusSchema = z.object({
  mode: optionalString,
  chain: z.string(),
  allChains: optionalBoolean,
  chains: z.array(z.string()).optional(),
  warnings: z.array(warningSchema).optional(),
  status: optionalString,
  requiresMigration: optionalBoolean,
  requiresWebsiteRecovery: optionalBoolean,
  isFullyMigrated: optionalBoolean,
  readinessResolved: optionalBoolean,
  submissionSupported: optionalBoolean,
  requiredChainIds: z.array(z.number()).optional(),
  migratedChainIds: z.array(z.number()).optional(),
  missingChainIds: z.array(z.number()).optional(),
  websiteRecoveryChainIds: z.array(z.number()).optional(),
  unresolvedChainIds: z.array(z.number()).optional(),
  chainReadiness: z.array(z.record(z.unknown())).optional(),
  externalGuidance: externalGuidanceSchema.optional(),
  nextActions: optionalNextActions,
});

const historyEventSchema = z.object({
  type: optionalString,
  asset: optionalString,
  poolAddress: optionalString,
  poolAccountNumber: optionalNumber,
  poolAccountId: optionalString,
  value: optionalString,
  blockNumber: optionalString,
  txHash: optionalString,
  explorerUrl: optionalString,
});

const historySchema = z.object({
  mode: optionalString,
  chain: z.string(),
  page: optionalNumber,
  perPage: optionalNumber,
  total: z.number().nullable().optional(),
  totalPages: z.number().nullable().optional(),
  lastSyncTime: optionalNullableString,
  syncSkipped: optionalBoolean,
  events: z.array(historyEventSchema),
  nextActions: optionalNextActions,
});

const commandDetailSchema = z.object({
  command: optionalString,
  description: optionalString,
  group: optionalString,
  aliases: z.array(z.string()).optional(),
  execution: optionalString,
  usage: optionalString,
  flags: z.array(z.string()).optional(),
  globalFlags: z.array(z.string()).optional(),
  requiresInit: optionalBoolean,
  expectedLatencyClass: optionalString,
  safeReadOnly: optionalBoolean,
  expectedNextActionWhen: z.array(z.string()).optional(),
  phaseGraph: optionalUnknown,
  phaseGraphRef: optionalString,
  sideEffectClass: optionalString,
  touchesFunds: optionalBoolean,
  requiresHumanReview: optionalBoolean,
  preferredSafeVariant: optionalUnknown,
  prerequisites: z.array(z.string()).optional(),
  examples: z.array(z.string()).optional(),
  structuredExamples: z.array(z.record(z.unknown())).optional(),
  jsonFields: optionalString,
  jsonVariants: z.array(z.string()).optional(),
  safetyNotes: z.array(z.string()).optional(),
  supportsUnsigned: optionalBoolean,
  supportsDryRun: optionalBoolean,
  agentFlagNames: z.array(z.string()).optional(),
  agentWorkflowNotes: z.array(z.string()).optional(),
  nextActions: optionalNextActions,
});

const describeSchema = z.union([
  commandDetailSchema,
  z.object({
    mode: z.literal("describe-index"),
    commands: z.array(z.object({
      command: z.string(),
      description: z.string(),
      group: z.string(),
    })),
    envelopeRoots: z.array(z.string()),
    nextActions: optionalNextActions,
  }),
  z.object({
    path: z.string(),
    schema: z.unknown(),
    nextActions: optionalNextActions,
  }),
]);

const completionSchema = z.object({
  mode: optionalString,
  shell: optionalString,
  completionScript: optionalString,
  cword: optionalNumber,
  candidates: z.array(z.string()).optional(),
  scriptPath: optionalString,
  profilePath: optionalString,
  scriptCreated: optionalBoolean,
  scriptUpdated: optionalBoolean,
  profileCreated: optionalBoolean,
  profileUpdated: optionalBoolean,
  bootstrapProfilePath: optionalString,
  bootstrapProfileCreated: optionalBoolean,
  bootstrapProfileUpdated: optionalBoolean,
  reloadHint: optionalString,
  nextActions: optionalNextActions,
});

const commandPayloadSchemas: Record<CommandPath, z.ZodTypeAny> = {
  init: z.object({
    mode: optionalString,
    operation: optionalString,
    status: optionalString,
    setupMode: optionalString,
    readiness: optionalString,
    effectiveChain: optionalString,
    defaultChain: optionalString,
    signerKeySet: optionalBoolean,
    mnemonicImported: optionalBoolean,
    backupFilePath: z.string().nullable().optional(),
    recoveryPhraseRedacted: optionalBoolean,
    recoveryPhrase: optionalString,
    restoreDiscovery: optionalUnknown,
    warning: optionalString,
    dryRun: optionalBoolean,
    recoveryPhraseSource: optionalString,
    signerKeySource: optionalString,
    backupCaptureMode: optionalString,
    backupFileWouldWrite: optionalBoolean,
    overwriteExisting: optionalBoolean,
    overwritePromptRequired: optionalBoolean,
    writeTargets: z.array(z.string()).optional(),
    humanCommand: optionalString,
    agentResumeCommand: optionalString,
    secretTransferRequired: optionalBoolean,
    nextStep: optionalString,
    nextActions: optionalNextActions,
  }),
  upgrade: z.object({
    mode: z.literal("upgrade").optional(),
    status: optionalString,
    currentVersion: optionalString,
    latestVersion: z.string().nullable().optional(),
    updateAvailable: optionalBoolean,
    performed: optionalBoolean,
    command: z.string().nullable().optional(),
    installContext: z.record(z.unknown()).optional(),
    installedVersion: z.string().nullable().optional(),
    releaseHighlights: z.array(z.string()).optional(),
    externalGuidance: externalGuidanceSchema.optional(),
    nextActions: optionalNextActions,
  }),
  config: configSchema,
  "config list": configSchema,
  "config get": configSchema,
  "config set": configSchema,
  "config unset": configSchema,
  "config path": configSchema,
  "config profile": configSchema,
  "config profile list": configSchema,
  "config profile create": configSchema,
  "config profile active": configSchema,
  "config profile use": configSchema,
  flow: flowSchema,
  simulate: dryRunBaseSchema,
  "flow start": flowSchema,
  "flow watch": flowSchema,
  "flow status": flowSchema,
  "flow step": flowSchema,
  "flow ragequit": flowSchema,
  pools: z.object({
    chain: z.string(),
    requestedChain: z.string().nullable().optional(),
    chainSummaries: z.array(z.object({
      chain: z.string(),
      pools: z.number(),
      error: z.string().nullable(),
    })).optional(),
    search: z.string().nullable(),
    sort: z.string(),
    pools: z.array(poolBaseSchema).optional(),
    asset: optionalString,
    tokenAddress: optionalString,
    pool: optionalString,
    scope: optionalString,
    decimals: optionalNumber,
    minimumDeposit: optionalString,
    vettingFeeBPS: optionalString,
    maxRelayFeeBPS: optionalString,
    myFunds: optionalUnknown,
    myFundsWarning: optionalString,
    recentActivity: optionalUnknown,
    recentActivityUnavailable: optionalBoolean,
    warnings: z.array(warningSchema).optional(),
    nextActions: optionalNextActions,
  }),
  activity: activitySchema,
  stats: statsSchema,
  "protocol-stats": statsSchema.extend({
    mode: z.literal("global-stats").optional(),
    command: z.string().optional(),
  }),
  "pool-stats": statsSchema.extend({
    mode: z.literal("pool-stats").optional(),
    command: z.string().optional(),
    asset: z.string(),
    pool: z.string(),
    scope: z.string(),
  }),
  status: z.object({
    mode: optionalString,
    configExists: z.boolean(),
    configDir: z.string().nullable(),
    defaultChain: z.string().nullable(),
    selectedChain: z.string().nullable(),
    rpcUrl: z.string().nullable().optional(),
    rpcIsCustom: optionalBoolean,
    recoveryPhraseSet: z.boolean(),
    signerKeySet: z.boolean(),
    signerKeyValid: z.boolean(),
    signerAddress: z.string().nullable().optional(),
    signerBalance: optionalString,
    signerBalanceDecimals: optionalNumber,
    signerBalanceSymbol: optionalString,
    entrypoint: z.string().nullable().optional(),
    aspHost: z.string().nullable().optional(),
    relayerHost: z.string().nullable().optional(),
    accountFiles: z.array(z.record(z.unknown())).optional(),
    readyForDeposit: z.boolean(),
    readyForWithdraw: z.boolean(),
    readyForUnsigned: z.boolean(),
    recommendedMode: z.string(),
    blockingIssues: z.array(z.record(z.unknown())).optional(),
    warnings: z.array(z.record(z.unknown())).optional(),
    aspLive: optionalBoolean,
    rpcLive: optionalBoolean,
    relayerLive: optionalBoolean,
    rpcBlockNumber: optionalString,
    pending: optionalUnknown,
    recoveryTable: optionalUnknown,
    phaseGraphRef: optionalString,
    nextActions: optionalNextActions,
  }),
  "tx-status": z.object({
    operation: z.literal("tx-status"),
    submissionId: z.string(),
    sourceOperation: optionalString,
    sourceCommand: optionalString,
    chain: z.string(),
    asset: optionalString,
    poolAccountId: optionalString,
    poolAccountNumber: optionalNumber,
    workflowId: optionalString,
    recipient: optionalString,
    broadcastMode: optionalString,
    broadcastSourceOperation: optionalString,
    createdAt: optionalString,
    updatedAt: optionalString,
    status: optionalString,
    estimatedConfirmationSeconds: optionalNumber,
    pollingRecommendation: optionalString,
    reconciliationRequired: optionalBoolean,
    localStateSynced: optionalBoolean,
    warningCode: optionalString,
    lastError: z.record(z.unknown()).optional(),
    transactions: z.array(z.record(z.unknown())).optional(),
    nextActions: optionalNextActions,
  }),
  capabilities: z.object({
    commands: z.array(z.record(z.unknown())),
    commandDetails: z.record(z.record(z.unknown())),
    executionRoutes: z.record(z.record(z.unknown())),
    globalFlags: z.array(z.record(z.unknown())),
    exitCodes: z.array(z.record(z.unknown())),
    envVars: z.array(z.record(z.unknown())),
    agentWorkflow: z.array(z.string()),
    agentNotes: z.record(z.string()),
    schemas: z.record(z.unknown()),
    supportedChains: z.array(z.record(z.unknown())),
    protocol: z.record(z.unknown()),
    runtime: z.record(z.unknown()),
    safeReadOnlyCommands: z.array(z.string()),
    jsonOutputContract: z.string(),
    documentation: z.object({
      reference: z.string(),
      agentGuide: z.string(),
      changelog: z.string(),
      runtimeUpgrades: optionalString,
      jsonContract: optionalString,
      envelopeSchemas: optionalString,
      errorCodes: optionalString,
    }).optional(),
    nextActions: optionalNextActions,
  }),
  describe: describeSchema,
  guide: z.object({
    mode: optionalString,
    topic: optionalString,
    topics: z.array(z.record(z.unknown())).optional(),
    help: optionalString,
    nextActions: optionalNextActions,
  }),
  deposit: transactionResultBaseSchema.extend({
    operation: z.literal("deposit"),
    workflowId: optionalString,
    approvalTxHash: z.string().nullable().optional(),
    committedValue: z.string().nullable().optional(),
    estimatedCommitted: z.string().nullable().optional(),
    vettingFeeBPS: optionalString,
    vettingFeeAmount: optionalString,
    feesApply: optionalBoolean,
    label: z.string().nullable().optional(),
  }),
  withdraw: transactionResultBaseSchema.extend({
    operation: z.literal("withdraw"),
    mode: z.enum(["relayed", "direct"]).optional(),
    recipient: optionalString,
    feeBPS: z.string().nullable().optional(),
    relayerHost: optionalString,
    quoteRefreshCount: optionalNumber,
    extraGas: optionalBoolean,
    extraGasFundAmount: z.string().nullable().optional(),
    remainingBalance: optionalString,
    rootMatchedAtProofTime: optionalBoolean,
    privacyCostManifest: optionalUnknown,
    anonymitySet: z.object({
      eligible: z.number(),
      total: z.number(),
      percentage: z.number(),
    }).optional(),
  }),
  "withdraw quote": z.object({
    mode: z.literal("relayed-quote").optional(),
    chain: z.string(),
    asset: z.string(),
    amount: z.string(),
    recipient: optionalString,
    minWithdrawAmount: optionalString,
    minWithdrawAmountFormatted: optionalString,
    baseFeeBPS: optionalString,
    quoteFeeBPS: optionalString,
    feeAmount: optionalString,
    netAmount: optionalString,
    feeCommitmentPresent: optionalBoolean,
    quoteExpiresAt: optionalString,
    relayTxCost: optionalString,
    relayerHost: optionalString,
    quoteRefreshCount: optionalNumber,
    extraGas: optionalBoolean,
    extraGasFundAmount: optionalString,
    extraGasTxCost: optionalString,
    isTestnet: optionalBoolean,
    anonymitySet: z.record(z.unknown()).optional(),
    warnings: z.array(warningSchema).optional(),
    nextActions: optionalNextActions,
  }),
  recipients: recipientsSchema,
  "recipients list": recipientsSchema,
  "recipients add": recipientsSchema,
  "recipients remove": recipientsSchema,
  "recipients clear": recipientsSchema,
  "withdraw recipients": recipientsSchema,
  "withdraw recipients list": recipientsSchema,
  "withdraw recipients add": recipientsSchema,
  "withdraw recipients remove": recipientsSchema,
  "withdraw recipients clear": recipientsSchema,
  ragequit: transactionResultBaseSchema.extend({
    operation: z.literal("ragequit"),
    destinationAddress: optionalString,
    privacyCostManifest: optionalUnknown,
  }),
  "simulate deposit": dryRunBaseSchema.extend({
    operation: z.literal("deposit").optional(),
    estimatedCommitted: optionalString,
    vettingFeeBPS: optionalString,
    vettingFeeAmount: optionalString,
    feesApply: optionalBoolean,
  }),
  "simulate withdraw": dryRunBaseSchema.extend({
    operation: z.literal("withdraw").optional(),
    recipient: optionalString,
    poolAccountNumber: optionalNumber,
    poolAccountId: optionalString,
    selectedCommitmentLabel: optionalString,
    selectedCommitmentValue: optionalString,
    proofPublicSignals: optionalUnknown,
    feeBPS: optionalString,
    quoteExpiresAt: optionalString,
    relayerHost: optionalString,
    quoteRefreshCount: optionalNumber,
    extraGas: optionalBoolean,
    anonymitySet: z.record(z.unknown()).optional(),
  }),
  "simulate ragequit": dryRunBaseSchema.extend({
    operation: z.literal("ragequit").optional(),
    poolAccountNumber: optionalNumber,
    poolAccountId: optionalString,
    destinationAddress: optionalString,
  }),
  broadcast: z.object({
    mode: z.literal("broadcast").optional(),
    broadcastMode: optionalString,
    sourceOperation: optionalString,
    chain: optionalString,
    validatedOnly: optionalBoolean,
    submissionId: z.string().nullable().optional(),
    submittedBy: optionalString,
    transactions: z.array(z.record(z.unknown())).optional(),
    localStateUpdated: optionalBoolean,
    warnings: z.array(warningSchema).optional(),
    nextActions: optionalNextActions,
  }),
  accounts: accountsSchema,
  migrate: migrateStatusSchema,
  "migrate status": migrateStatusSchema,
  history: historySchema,
  sync: z.object({
    isFinal: optionalBoolean,
    chain: z.string(),
    syncedPools: optionalNumber,
    syncedSymbols: z.array(z.string()).optional(),
    availablePoolAccounts: optionalNumber,
    previousAvailablePoolAccounts: optionalNumber,
    durationMs: optionalNumber,
    scannedFromBlock: optionalString,
    scannedToBlock: optionalString,
    eventCounts: z.record(z.number()).optional(),
    lastSyncTime: optionalString,
    nextActions: optionalNextActions,
  }),
  completion: completionSchema,
};

function commandEnvelope(payloadSchema: z.ZodTypeAny): z.ZodTypeAny {
  return z.union([
    successEnvelopeSchema.and(payloadSchema),
    errorEnvelopeSchema,
  ]);
}

export const commandEnvelopeSchemas = Object.fromEntries(
  COMMAND_PATHS.map((command) => [
    command,
    commandEnvelope(commandPayloadSchemas[command]).describe(command),
  ]),
) as Record<CommandPath, z.ZodTypeAny>;

export type CommandEnvelopeSchemas = typeof commandEnvelopeSchemas;
export type CommandEnvelope =
  | z.infer<typeof successEnvelopeSchema>
  | z.infer<typeof errorEnvelopeSchema>;
