/* AUTO-GENERATED by scripts/generate-command-discovery-static.mjs - DO NOT EDIT */

import type { CapabilitiesPayload } from "../types.js";

export const STATIC_COMMAND_PATHS = [
  "init",
  "flow",
  "flow start",
  "flow watch",
  "flow status",
  "flow ragequit",
  "pools",
  "activity",
  "stats",
  "stats global",
  "stats pool",
  "status",
  "capabilities",
  "describe",
  "guide",
  "deposit",
  "withdraw",
  "withdraw quote",
  "ragequit",
  "accounts",
  "migrate",
  "migrate status",
  "history",
  "sync",
  "completion"
] as const;

export type StaticCommandPath = (typeof STATIC_COMMAND_PATHS)[number];

const STATIC_COMMAND_PATH_SET = new Set<string>(STATIC_COMMAND_PATHS);

const STATIC_COMMAND_ALIAS_MAP: Record<string, StaticCommandPath> = {
  "exit": "ragequit"
};

export const STATIC_CAPABILITIES_PAYLOAD: CapabilitiesPayload = {
  "commands": [
    {
      "name": "init",
      "description": "Initialize wallet and configuration",
      "usage": "init",
      "flags": [
        "--mnemonic <phrase>",
        "--mnemonic-file <path>",
        "--mnemonic-stdin",
        "--private-key <key>",
        "--private-key-file <path>",
        "--private-key-stdin",
        "--default-chain <chain>",
        "--force",
        "--show-mnemonic"
      ],
      "agentFlags": "--agent --default-chain <chain> --show-mnemonic",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "flow",
      "description": "Run the easy-path deposit-to-withdraw workflow",
      "usage": "flow",
      "flags": [
        "start <amount> <asset> --to <address>",
        "watch [workflowId|latest]",
        "status [workflowId|latest]",
        "ragequit [workflowId|latest]"
      ],
      "agentFlags": "start <amount> <asset> --to <address> --agent (or: watch/status/ragequit --agent)",
      "requiresInit": false,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "flow start",
      "description": "Deposit now and save a later private withdrawal workflow",
      "usage": "flow start <amount> <asset> --to <address>",
      "flags": [
        "--to <address>",
        "--watch",
        "--new-wallet",
        "--export-new-wallet <path>"
      ],
      "agentFlags": "--agent --to <address> [--watch] [--new-wallet] [--export-new-wallet <path>]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "flow watch",
      "description": "Poll ASP approval and withdraw privately when ready",
      "usage": "flow watch [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "agentFlags": "--agent [workflowId|latest]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "flow status",
      "description": "Show the saved easy-path workflow state",
      "usage": "flow status [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "agentFlags": "--agent [workflowId|latest]",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "flow ragequit",
      "description": "Recover a saved workflow publicly via ragequit",
      "usage": "flow ragequit [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "agentFlags": "--agent [workflowId|latest]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "pools",
      "description": "List available pools and assets",
      "usage": "pools",
      "flags": [
        "--all-chains",
        "--search <query>",
        "--sort <mode>"
      ],
      "agentFlags": "--agent [--all-chains] [--search <query>] [--sort <mode>]",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "activity",
      "description": "Show public activity feed",
      "usage": "activity",
      "flags": [
        "--asset <symbol|address>",
        "--page <n>",
        "--limit <n>"
      ],
      "agentFlags": "--agent [--asset <symbol>] [--page <n>] [--limit <n>]",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "stats",
      "description": "Show public statistics",
      "usage": "stats",
      "flags": [
        "global",
        "pool --asset <symbol|address>"
      ],
      "agentFlags": "global --agent (or: pool --asset <symbol> --agent)",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "stats global",
      "description": "Show global Privacy Pools statistics (all-time and last 24h)",
      "usage": "stats global",
      "flags": [],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "stats pool",
      "description": "Show statistics for a specific pool (all-time and last 24h)",
      "usage": "stats pool --asset <symbol|address>",
      "flags": [
        "--asset <symbol|address>"
      ],
      "agentFlags": "--agent --asset <symbol>",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "describe",
      "description": "Describe one command for runtime agent introspection",
      "usage": "describe <command...>",
      "flags": [
        "<command...>"
      ],
      "agentFlags": "--agent <command...>",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "deposit",
      "description": "Deposit into a pool",
      "usage": "deposit <amount> [asset]",
      "flags": [
        "--asset <symbol|address>",
        "--unsigned [envelope|tx]",
        "--dry-run",
        "--ignore-unique-amount"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "withdraw",
      "description": "Withdraw from a pool",
      "usage": "withdraw [amount] [asset] --to <address>",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>",
        "--from-pa <PA-#>",
        "--all",
        "--direct",
        "--extra-gas",
        "--no-extra-gas",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "withdraw quote",
      "description": "Request relayer quote and limits without generating a proof",
      "usage": "withdraw quote <amount|asset> [amount]",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "accounts",
      "description": "List your Pool Accounts (individual deposit lineages) with balances",
      "usage": "accounts",
      "flags": [
        "--no-sync",
        "--all-chains",
        "--details",
        "--summary",
        "--pending-only"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "migrate",
      "description": "Inspect legacy migration readiness on CLI-supported chains",
      "usage": "migrate",
      "flags": [
        "status [--all-chains]"
      ],
      "agentFlags": "status --agent [--all-chains]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "migrate status",
      "description": "Show legacy migration readiness on CLI-supported chains",
      "usage": "migrate status",
      "flags": [
        "--all-chains"
      ],
      "agentFlags": "--agent [--all-chains]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "history",
      "description": "Show chronological event history (deposits, withdrawals, ragequits)",
      "usage": "history",
      "flags": [
        "--no-sync",
        "--limit <n>"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "sync",
      "description": "Force-sync local account state from onchain events",
      "usage": "sync",
      "flags": [
        "-a, --asset <symbol|address>"
      ],
      "agentFlags": "--agent [--asset <symbol>]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "status",
      "description": "Show configuration and check connection health",
      "usage": "status",
      "flags": [
        "--check",
        "--no-check",
        "--check-rpc",
        "--check-asp"
      ],
      "agentFlags": "--agent [--no-check] [--check-rpc] [--check-asp]",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "ragequit",
      "description": "Publicly withdraw funds to your deposit address",
      "aliases": [
        "exit"
      ],
      "usage": "ragequit [asset] --from-pa <PA-#>",
      "flags": [
        "--asset <symbol|address>",
        "--from-pa <PA-#>",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "guide",
      "description": "Show usage guide, workflow, and reference",
      "usage": "guide",
      "flags": [],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "completion",
      "description": "Generate shell completion script",
      "usage": "completion",
      "flags": [
        "[shell]",
        "--shell <shell>"
      ],
      "agentFlags": "--agent <shell>",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "capabilities",
      "description": "Describe CLI capabilities for agent discovery",
      "usage": "capabilities",
      "flags": [],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    }
  ],
  "commandDetails": {
    "init": {
      "command": "init",
      "description": "Initialize wallet and configuration",
      "aliases": [],
      "usage": "init",
      "flags": [
        "--mnemonic <phrase>",
        "--mnemonic-file <path>",
        "--mnemonic-stdin",
        "--private-key <key>",
        "--private-key-file <path>",
        "--private-key-stdin",
        "--default-chain <chain>",
        "--force",
        "--show-mnemonic"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools init",
        "privacy-pools init --yes --default-chain mainnet",
        "privacy-pools init --force --yes --default-chain mainnet",
        "privacy-pools init --agent --default-chain mainnet --show-mnemonic",
        "privacy-pools init --mnemonic \"word ...\" --private-key 0x...",
        "privacy-pools init --mnemonic-file ./my-mnemonic.txt --private-key-file ./my-key.txt",
        "cat phrase.txt | privacy-pools init --mnemonic-stdin --yes --default-chain mainnet"
      ],
      "jsonFields": "{ defaultChain, signerKeySet, recoveryPhraseRedacted? | recoveryPhrase?, warning?, nextActions?: [{ command, reason, when, args?, options?, runnable? }] }",
      "jsonVariants": [],
      "safetyNotes": [
        "The recovery phrase and signer key are independent secrets: the phrase controls deposit privacy, the key pays gas. Neither is derived from the other.",
        "Newly generated recovery phrases use 24 words (256-bit entropy). Imported recovery phrases may still be 12 or 24 words.",
        "Legacy pre-upgrade accounts may need website migration or website-based recovery before the CLI can safely restore them."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "When generating a new recovery phrase in machine mode, pass --show-mnemonic and capture it immediately.",
        "When importing an existing recovery phrase, nextActions points to accounts --agent --all-chains so the CLI can check for Pool Accounts across mainnets and testnets."
      ]
    },
    "flow": {
      "command": "flow",
      "description": "Run the easy-path deposit-to-withdraw workflow",
      "aliases": [],
      "usage": "flow",
      "flags": [
        "start <amount> <asset> --to <address>",
        "watch [workflowId|latest]",
        "status [workflowId|latest]",
        "ragequit [workflowId|latest]"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init for start/watch/ragequit; saved workflow for status"
      ],
      "examples": [
        "privacy-pools flow start 0.1 ETH --to 0xRecipient...",
        "privacy-pools flow start 0.1 ETH --to 0xRecipient... --watch",
        "privacy-pools flow start 100 USDC --to 0xRecipient... --new-wallet --export-new-wallet ./flow-wallet.txt",
        "privacy-pools flow watch",
        "privacy-pools flow status latest",
        "privacy-pools flow ragequit latest"
      ],
      "jsonFields": null,
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "flow start": {
      "command": "flow start",
      "description": "Deposit now and save a later private withdrawal workflow",
      "aliases": [],
      "usage": "flow start <amount> <asset> --to <address>",
      "flags": [
        "--to <address>",
        "--watch",
        "--new-wallet",
        "--export-new-wallet <path>"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools flow start 0.1 ETH --to 0xRecipient...",
        "privacy-pools flow start 100 USDC --to 0xRecipient... --chain mainnet",
        "privacy-pools flow start 100 USDC --to 0xRecipient... --new-wallet --export-new-wallet ./flow-wallet.txt",
        "privacy-pools flow start 0.1 ETH --to 0xRecipient... --watch --agent"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"start\", workflowId, phase, walletMode?, walletAddress?, requiredNativeFunding?, requiredTokenFunding?, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId?, poolAccountNumber?, depositTxHash?, depositBlockNumber?, depositExplorerUrl?, committedValue?, aspStatus?, withdrawTxHash?, withdrawBlockNumber?, withdrawExplorerUrl?, ragequitTxHash?, ragequitBlockNumber?, ragequitExplorerUrl?, lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [
        "The deposit is still public and reviewed by the ASP before private withdrawal is possible.",
        "In machine modes, non-round flow amounts are rejected by default for the same privacy reasons as deposit. Prefer round amounts unless you intentionally accept that tradeoff.",
        "--export-new-wallet is only valid with --new-wallet.",
        "Non-interactive workflow wallets require --export-new-wallet so the generated private key is backed up before the flow starts.",
        "Manual commands remain the advanced/manual path when you need custom control over Pool Account selection, amount, or withdrawal mode."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "With --new-wallet, the flow stays attached automatically and waits for funding, deposit, approval, and withdrawal unless you detach with Ctrl-C.",
        "Use --watch to stay attached on configured-wallet workflows; otherwise the workflow is persisted locally and flow watch <workflowId> is the canonical resume path."
      ]
    },
    "flow watch": {
      "command": "flow watch",
      "description": "Poll ASP approval and withdraw privately when ready",
      "aliases": [],
      "usage": "flow watch [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools flow watch",
        "privacy-pools flow watch latest --agent",
        "privacy-pools flow watch 123e4567-e89b-12d3-a456-426614174000"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"watch\", workflowId, phase, walletMode?, walletAddress?, requiredNativeFunding?, requiredTokenFunding?, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId?, poolAccountNumber?, depositTxHash?, depositBlockNumber?, depositExplorerUrl?, committedValue?, aspStatus?, withdrawTxHash?, withdrawBlockNumber?, withdrawExplorerUrl?, ragequitTxHash?, ragequitBlockNumber?, ragequitExplorerUrl?, lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [
        "Paused states are successful workflow states, not CLI errors. Declined workflows surface flow ragequit as the canonical recovery path, and PoA-required workflows pause until the external Proof of Association step is completed."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "New-wallet workflows wait for funding automatically. ERC20 workflows require both the token amount and a native ETH gas reserve in the generated wallet before the public deposit can proceed.",
        "When the saved Pool Account is approved, flow watch performs the relayed private withdrawal automatically using the saved recipient and the full remaining balance of that same Pool Account.",
        "flow watch keeps polling until the saved workflow changes or finishes. If your automation should stop after a fixed duration, wrap the CLI call in your own external timeout."
      ]
    },
    "flow status": {
      "command": "flow status",
      "description": "Show the saved easy-path workflow state",
      "aliases": [],
      "usage": "flow status [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "prerequisites": [
        "saved workflow (usually created after init)"
      ],
      "examples": [
        "privacy-pools flow status",
        "privacy-pools flow status latest --agent",
        "privacy-pools flow status 123e4567-e89b-12d3-a456-426614174000"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"status\", workflowId, phase, walletMode?, walletAddress?, requiredNativeFunding?, requiredTokenFunding?, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId?, poolAccountNumber?, depositTxHash?, depositBlockNumber?, depositExplorerUrl?, committedValue?, aspStatus?, withdrawTxHash?, withdrawBlockNumber?, withdrawExplorerUrl?, ragequitTxHash?, ragequitBlockNumber?, ragequitExplorerUrl?, lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "flow ragequit": {
      "command": "flow ragequit",
      "description": "Recover a saved workflow publicly via ragequit",
      "aliases": [],
      "usage": "flow ragequit [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools flow ragequit",
        "privacy-pools flow ragequit latest --agent",
        "privacy-pools flow ragequit 123e4567-e89b-12d3-a456-426614174000"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"ragequit\", workflowId, phase, walletMode?, walletAddress?, requiredNativeFunding?, requiredTokenFunding?, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId?, poolAccountNumber?, depositTxHash?, depositBlockNumber?, depositExplorerUrl?, committedValue?, aspStatus?, withdrawTxHash?, withdrawBlockNumber?, withdrawExplorerUrl?, ragequitTxHash?, ragequitBlockNumber?, ragequitExplorerUrl?, lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [
        "This is a public recovery path. It exits to the original deposit address and does not preserve privacy.",
        "Configured-wallet recovery only works when the current signer still matches the original depositor address saved with the workflow."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "pools": {
      "command": "pools",
      "description": "List available pools and assets",
      "aliases": [],
      "usage": "pools",
      "flags": [
        "--all-chains",
        "--search <query>",
        "--sort <mode>"
      ],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools pools",
        "privacy-pools pools ETH",
        "privacy-pools pools BOLD --chain mainnet",
        "privacy-pools pools --all-chains --sort tvl-desc",
        "privacy-pools pools --search usdc --sort asset-asc",
        "privacy-pools pools --agent --chain mainnet"
      ],
      "jsonFields": "{ chain?, allChains?, chains?, search, sort, pools: [{ chain?, asset, tokenAddress, pool, scope, totalDepositsCount, totalDepositsValue, acceptedDepositsValue, pendingDepositsValue, ... }], warnings? }",
      "jsonVariants": [
        "detail (<asset>): { chain, asset, tokenAddress, pool, scope, ..., myFunds?, myFundsWarning?, recentActivity? }",
        "detail myFunds: { balance, usdValue, poolAccounts, pendingCount, poiRequiredCount, declinedCount, accounts: [{ id, status, aspStatus, value }] }"
      ],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "In pools JSON, 'asset' is the symbol for CLI follow-up commands and 'tokenAddress' is the contract address."
      ]
    },
    "activity": {
      "command": "activity",
      "description": "Show public activity feed",
      "aliases": [],
      "usage": "activity",
      "flags": [
        "--asset <symbol|address>",
        "--page <n>",
        "--limit <n>"
      ],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools activity",
        "privacy-pools activity --page 2 --limit 20",
        "privacy-pools activity --asset ETH",
        "privacy-pools activity --asset USDC --agent --chain mainnet"
      ],
      "jsonFields": "{ mode, chain, chains?, page, perPage, total, totalPages, chainFiltered?, note?, asset?, pool?, scope?, events: [{ type, txHash, explorerUrl, reviewStatus, amountRaw, amountFormatted, poolSymbol, poolAddress, chainId, timestamp }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "stats": {
      "command": "stats",
      "description": "Show public statistics",
      "aliases": [],
      "usage": "stats",
      "flags": [
        "global",
        "pool --asset <symbol|address>"
      ],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools stats global",
        "privacy-pools stats pool --asset ETH",
        "privacy-pools stats pool --asset USDC --agent --chain mainnet"
      ],
      "jsonFields": null,
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "stats global": {
      "command": "stats global",
      "description": "Show global Privacy Pools statistics (all-time and last 24h)",
      "aliases": [],
      "usage": "stats global",
      "flags": [],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools stats global",
        "privacy-pools stats global --agent"
      ],
      "jsonFields": "{ mode, chain, chains?, cacheTimestamp?, allTime?, last24h?, perChain?: [{ chain, cacheTimestamp, allTime, last24h }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "stats pool": {
      "command": "stats pool",
      "description": "Show statistics for a specific pool (all-time and last 24h)",
      "aliases": [],
      "usage": "stats pool --asset <symbol|address>",
      "flags": [
        "--asset <symbol|address>"
      ],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools stats pool --asset ETH",
        "privacy-pools stats pool --asset USDC --agent --chain mainnet"
      ],
      "jsonFields": "{ mode, chain, asset, pool, scope, cacheTimestamp?, allTime?, last24h? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "status": {
      "command": "status",
      "description": "Show configuration and check connection health",
      "aliases": [],
      "usage": "status",
      "flags": [
        "--check",
        "--no-check",
        "--check-rpc",
        "--check-asp"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools status",
        "privacy-pools status --check",
        "privacy-pools status --no-check",
        "privacy-pools status --agent --check-rpc",
        "privacy-pools status --chain mainnet --rpc-url https://..."
      ],
      "jsonFields": "{ configExists, configDir, defaultChain, selectedChain, rpcUrl, rpcIsCustom, recoveryPhraseSet, signerKeySet, signerKeyValid, signerAddress, entrypoint, aspHost, accountFiles: [{ chain, chainId }], readyForDeposit, readyForWithdraw, readyForUnsigned, nextActions?: [{ command, reason, when, args?, options?, runnable? }], aspLive?, rpcLive?, rpcBlockNumber? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "capabilities": {
      "command": "capabilities",
      "description": "Describe CLI capabilities for agent discovery",
      "aliases": [],
      "usage": "capabilities",
      "flags": [],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools capabilities",
        "privacy-pools capabilities --agent"
      ],
      "jsonFields": "{ commands[], commandDetails{}, globalFlags[], agentWorkflow[], agentNotes{}, schemas{}, supportedChains[], safeReadOnlyCommands[], jsonOutputContract, documentation?: { reference, agentGuide, changelog } }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "describe": {
      "command": "describe",
      "description": "Describe one command for runtime agent introspection",
      "aliases": [],
      "usage": "describe <command...>",
      "flags": [
        "<command...>"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools describe withdraw",
        "privacy-pools describe withdraw quote --agent",
        "privacy-pools describe stats global --agent"
      ],
      "jsonFields": "{ command, description, aliases, usage, flags, globalFlags, requiresInit, expectedLatencyClass, safeReadOnly, prerequisites, examples, jsonFields, jsonVariants, safetyNotes, supportsUnsigned, supportsDryRun, agentWorkflowNotes }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "guide": {
      "command": "guide",
      "description": "Show usage guide, workflow, and reference",
      "aliases": [],
      "usage": "guide",
      "flags": [],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools guide",
        "privacy-pools guide --agent"
      ],
      "jsonFields": "{ mode: \"help\", help }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "deposit": {
      "command": "deposit",
      "description": "Deposit into a pool",
      "aliases": [],
      "usage": "deposit <amount> [asset]",
      "flags": [
        "--asset <symbol|address>",
        "--unsigned [envelope|tx]",
        "--dry-run",
        "--ignore-unique-amount"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools deposit 0.1 ETH",
        "privacy-pools deposit 100 USDC",
        "privacy-pools deposit 0.05 ETH --agent",
        "privacy-pools deposit 0.1 ETH --unsigned",
        "privacy-pools deposit 0.1 ETH --dry-run",
        "privacy-pools deposit 0.1 --asset ETH --chain mainnet"
      ],
      "jsonFields": "{ operation, txHash, amount, committedValue, asset, chain, poolAccountNumber, poolAccountId, poolAddress, scope, label, blockNumber, explorerUrl, nextActions?: [{ command, reason, when, args?, options?, runnable? }] }",
      "jsonVariants": [
        "--unsigned: { mode, operation, chain, asset, amount, precommitment, transactions[] }",
        "--unsigned tx: [{ to, data, value, valueHex, chainId }]",
        "--dry-run: { dryRun, operation, chain, asset, amount, poolAccountNumber, poolAccountId, precommitment, balanceSufficient }"
      ],
      "safetyNotes": [
        "Deposits are reviewed by the ASP before approval. Most approve within 1 hour; some may take up to 7 days.",
        "A vetting fee is deducted from the deposit amount by the pool's ASP.",
        "Only approved deposits can use withdraw, whether relayed or direct. Declined deposits must use ragequit/exit publicly. Deposits that require Proof of Association (PoA) must complete the PoA flow at tornado.0xbow.io before they can withdraw privately."
      ],
      "supportsUnsigned": true,
      "supportsDryRun": true,
      "agentWorkflowNotes": [
        "Poll accounts --chain <chain> --pending-only while the Pool Account remains pending; when it disappears from pending results, re-run accounts --chain <chain> to confirm whether aspStatus became approved, declined, or requires Proof of Association. Withdraw only after approval; ragequit if declined; complete Proof of Association at tornado.0xbow.io first if needed. Always preserve the same --chain scope for both polling and confirmation."
      ]
    },
    "withdraw": {
      "command": "withdraw",
      "description": "Withdraw from a pool",
      "aliases": [],
      "usage": "withdraw [amount] [asset] --to <address>",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>",
        "--from-pa <PA-#>",
        "--all",
        "--direct",
        "--extra-gas",
        "--no-extra-gas",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init (account state should be synced)"
      ],
      "examples": [
        "privacy-pools withdraw 0.05 ETH --to 0xRecipient...",
        "privacy-pools withdraw 0.05 ETH --to 0xRecipient... --from-pa PA-2",
        "privacy-pools withdraw --all ETH --to 0xRecipient...",
        "privacy-pools withdraw 50% ETH --to 0xRecipient...",
        "privacy-pools withdraw 0.1 ETH --to 0xRecipient... --dry-run",
        "privacy-pools withdraw quote 0.1 ETH --to 0xRecipient...",
        "privacy-pools withdraw 0.05 ETH --to 0xRecipient... --chain mainnet"
      ],
      "jsonFields": "{ operation, mode, txHash, blockNumber, amount, recipient, explorerUrl, poolAddress, scope, asset, chain, poolAccountNumber, poolAccountId, feeBPS, extraGas?, remainingBalance, anonymitySet?: { eligible, total, percentage }, nextActions?: [{ command, reason, when, args?, options?, runnable? }] }",
      "jsonVariants": [
        "direct: same fields but mode: \"direct\", feeBPS: null, no extraGas, and human output explains the onchain link between deposit and withdrawal.",
        "quote: { mode: \"relayed-quote\", chain, asset, amount, recipient, minWithdrawAmount, minWithdrawAmountFormatted, quoteFeeBPS, feeAmount, netAmount, feeCommitmentPresent, quoteExpiresAt, extraGas?, nextActions?: [{ command, reason, when, args?, options?, runnable? }] }",
        "--unsigned: { mode, operation, withdrawMode, chain, transactions[], ... }",
        "--unsigned tx: [{ to, data, value, valueHex, chainId }]",
        "--dry-run: { operation, mode, dryRun, amount, asset, chain, recipient, poolAccountNumber, poolAccountId, selectedCommitmentLabel, selectedCommitmentValue, proofPublicSignals, feeBPS?, quoteExpiresAt?, extraGas?, anonymitySet?: { eligible, total, percentage } }"
      ],
      "safetyNotes": [
        "Always prefer relayed withdrawals (the default). Direct withdrawals (--direct) are NOT privacy-preserving: they publicly link your deposit address and withdrawal address onchain. Only use --direct if you understand and accept the privacy trade-off.",
        "ASP approval is required for both relayed and direct withdrawals. Declined deposits must ragequit publicly to the original deposit address.",
        "Relayed withdrawals must also respect the relayer minimum. If a withdrawal would leave a positive remainder below that minimum, the CLI warns so you can withdraw less, use --all/100%, or choose a public recovery path later."
      ],
      "supportsUnsigned": true,
      "supportsDryRun": true,
      "agentWorkflowNotes": []
    },
    "withdraw quote": {
      "command": "withdraw quote",
      "description": "Request relayer quote and limits without generating a proof",
      "aliases": [],
      "usage": "withdraw quote <amount|asset> [amount]",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "medium",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools withdraw quote 0.1 ETH --to 0xRecipient...",
        "privacy-pools withdraw quote 100 USDC --agent --chain mainnet"
      ],
      "jsonFields": "{ mode: \"relayed-quote\", chain, asset, amount, recipient, minWithdrawAmount, minWithdrawAmountFormatted, quoteFeeBPS, feeAmount, netAmount, feeCommitmentPresent, quoteExpiresAt, extraGas?, nextActions?: [{ command, reason, when, args?, options?, runnable? }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "Quotes expire quickly; submit the withdrawal promptly after quoting if the fee is acceptable. Check runnable=false on nextActions for template commands that still need required user input."
      ]
    },
    "ragequit": {
      "command": "ragequit",
      "description": "Publicly withdraw funds to your deposit address",
      "aliases": [
        "exit"
      ],
      "usage": "ragequit [asset] --from-pa <PA-#>",
      "flags": [
        "--asset <symbol|address>",
        "--from-pa <PA-#>",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init (account state should be synced)"
      ],
      "examples": [
        "privacy-pools ragequit ETH --from-pa PA-1",
        "privacy-pools ragequit ETH --unsigned --from-pa PA-1",
        "privacy-pools ragequit ETH --dry-run --from-pa PA-1",
        "privacy-pools ragequit ETH --from-pa PA-1 --chain mainnet"
      ],
      "jsonFields": "{ operation, txHash, amount, asset, chain, poolAccountNumber, poolAccountId, poolAddress, scope, blockNumber, explorerUrl, nextActions?: [{ command, reason, when, args?, options?, runnable? }] }",
      "jsonVariants": [
        "--unsigned: { mode, operation, chain, asset, amount, transactions[] }",
        "--unsigned tx: [{ to, data, value, valueHex, chainId }]",
        "--dry-run: { dryRun, operation, chain, asset, amount, poolAccountNumber, poolAccountId, selectedCommitmentLabel, selectedCommitmentValue, proofPublicSignals }"
      ],
      "safetyNotes": [
        "Ragequit is public and irreversible and reveals the original deposit address onchain."
      ],
      "supportsUnsigned": true,
      "supportsDryRun": true,
      "agentWorkflowNotes": []
    },
    "accounts": {
      "command": "accounts",
      "description": "List your Pool Accounts (individual deposit lineages) with balances",
      "aliases": [],
      "usage": "accounts",
      "flags": [
        "--no-sync",
        "--all-chains",
        "--details",
        "--summary",
        "--pending-only"
      ],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools accounts",
        "privacy-pools accounts --all-chains",
        "privacy-pools accounts --details",
        "privacy-pools accounts --summary",
        "privacy-pools accounts --chain <name> --pending-only",
        "privacy-pools accounts --agent",
        "privacy-pools accounts --no-sync --chain mainnet"
      ],
      "jsonFields": "{ chain, allChains?, chains?, warnings?, accounts: [{ poolAccountNumber, poolAccountId, status, aspStatus, asset, scope, value, hash, label, blockNumber, txHash, explorerUrl, chain?, chainId? }], balances: [{ asset, balance, usdValue, poolAccounts, chain?, chainId? }], pendingCount, nextActions?: [{ command, reason, when, args?, options?, runnable? }] }",
      "jsonVariants": [
        "--summary: { chain, allChains?, chains?, warnings?, pendingCount, approvedCount, poiRequiredCount, declinedCount, unknownCount, spentCount, exitedCount, balances, nextActions? }",
        "--pending-only: { chain, allChains?, chains?, warnings?, accounts, pendingCount, nextActions? }"
      ],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "Without --chain, accounts aggregates all mainnet chains by default. Use --all-chains to include testnets.",
        "Use --summary or --pending-only to reduce JSON size for polling loops.",
        "When a Pool Account disappears from --pending-only results, re-run accounts without --pending-only to confirm whether it was approved, declined, or requires Proof of Association (tornado.0xbow.io) before choosing withdraw or ragequit."
      ]
    },
    "migrate": {
      "command": "migrate",
      "description": "Inspect legacy migration readiness on CLI-supported chains",
      "aliases": [],
      "usage": "migrate",
      "flags": [
        "status [--all-chains]"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": true,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools migrate status",
        "privacy-pools migrate status --chain mainnet",
        "privacy-pools migrate status --all-chains --agent"
      ],
      "jsonFields": null,
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "migrate status": {
      "command": "migrate status",
      "description": "Show legacy migration readiness on CLI-supported chains",
      "aliases": [],
      "usage": "migrate status",
      "flags": [
        "--all-chains"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": true,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools migrate status",
        "privacy-pools migrate status --chain mainnet",
        "privacy-pools migrate status --all-chains --agent"
      ],
      "jsonFields": "{ mode: \"migration-status\", chain, allChains?, chains?, warnings?, status, requiresMigration, requiresWebsiteRecovery, isFullyMigrated, readinessResolved, submissionSupported: false, requiredChainIds, migratedChainIds, missingChainIds, websiteRecoveryChainIds, unresolvedChainIds, chainReadiness: [{ chain, chainId, status, candidateLegacyCommitments, expectedLegacyCommitments, migratedCommitments, legacyMasterSeedNullifiedCount, hasPostMigrationCommitments, isMigrated, legacySpendableCommitments, upgradedSpendableCommitments, declinedLegacyCommitments, reviewStatusComplete, requiresMigration, requiresWebsiteRecovery, scopes }] }",
      "jsonVariants": [],
      "safetyNotes": [
        "This command is read-only. It never submits migration transactions and does not persist rebuilt account state.",
        "When readinessResolved is false, treat the result as incomplete and review the account in the Privacy Pools website before acting on it.",
        "This check is limited to chains currently supported by the CLI. Review beta or other website-only migration surfaces in the Privacy Pools website."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "Use this after init/import when the CLI warns that a legacy pre-upgrade account may need website migration or website-based recovery."
      ]
    },
    "history": {
      "command": "history",
      "description": "Show chronological event history (deposits, withdrawals, ragequits)",
      "aliases": [],
      "usage": "history",
      "flags": [
        "--no-sync",
        "--limit <n>"
      ],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools history",
        "privacy-pools history --limit 10",
        "privacy-pools history --agent",
        "privacy-pools history --no-sync --chain mainnet"
      ],
      "jsonFields": "{ chain, events: [{ type, asset, poolAddress, poolAccountNumber, poolAccountId, value, blockNumber, txHash, explorerUrl }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "sync": {
      "command": "sync",
      "description": "Force-sync local account state from onchain events",
      "aliases": [],
      "usage": "sync",
      "flags": [
        "-a, --asset <symbol|address>"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools sync",
        "privacy-pools sync --asset ETH --agent",
        "privacy-pools sync --chain mainnet"
      ],
      "jsonFields": "{ chain, syncedPools, availablePoolAccounts, syncedSymbols?, previousAvailablePoolAccounts? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "completion": {
      "command": "completion",
      "description": "Generate shell completion script",
      "aliases": [],
      "usage": "completion",
      "flags": [
        "[shell]",
        "--shell <shell>"
      ],
      "globalFlags": [
        "-j, --json",
        "-y, --yes",
        "-c, --chain <name>",
        "-r, --rpc-url <url>",
        "-q, --quiet",
        "-v, --verbose",
        "--no-banner",
        "--no-color",
        "--agent",
        "--timeout <seconds>"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools completion zsh > ~/.zsh/completions/_privacy-pools",
        "privacy-pools completion bash > ~/.local/share/bash-completion/completions/privacy-pools",
        "privacy-pools completion fish > ~/.config/fish/completions/privacy-pools.fish",
        "privacy-pools completion powershell >> $PROFILE"
      ],
      "jsonFields": "{ mode, shell, completionScript }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    }
  },
  "globalFlags": [
    {
      "flag": "-j, --json",
      "description": "Machine-readable JSON output on stdout"
    },
    {
      "flag": "--format <format>",
      "description": "Output format: table (default), csv, json"
    },
    {
      "flag": "-y, --yes",
      "description": "Skip confirmation prompts"
    },
    {
      "flag": "-c, --chain <name>",
      "description": "Target chain (mainnet, arbitrum, optimism, ...)"
    },
    {
      "flag": "-r, --rpc-url <url>",
      "description": "Override RPC URL"
    },
    {
      "flag": "-q, --quiet",
      "description": "Suppress non-essential stderr output"
    },
    {
      "flag": "-v, --verbose",
      "description": "Enable verbose/debug output"
    },
    {
      "flag": "--no-banner",
      "description": "Disable ASCII banner output"
    },
    {
      "flag": "--no-color",
      "description": "Disable colored output (also respects NO_COLOR env var)"
    },
    {
      "flag": "--agent",
      "description": "Machine-friendly mode (alias for --json --yes --quiet)"
    },
    {
      "flag": "--timeout <seconds>",
      "description": "Network/transaction timeout in seconds (default: 30)"
    }
  ],
  "agentWorkflow": [
    "1. privacy-pools status --agent",
    "2. privacy-pools init --agent --default-chain <chain> --show-mnemonic",
    "3. privacy-pools pools --agent --chain <chain>",
    "4. privacy-pools flow start <amount> <asset> --to <address> --agent --chain <chain>",
    "5. privacy-pools flow watch [workflowId|latest] --agent",
    "6. privacy-pools flow ragequit [workflowId|latest] --agent  (if the saved workflow is declined)",
    "7. privacy-pools deposit <amount> --asset <symbol> --agent --chain <chain>  (manual alternative)",
    "8. privacy-pools accounts --agent --chain <chain> --pending-only  (reviewed entries disappear; confirm approved vs declined vs poi_required with accounts --agent --chain <chain>)",
    "9. privacy-pools withdraw <amount> --asset <symbol> --to <address> --agent --chain <chain>"
  ],
  "agentNotes": {
    "polling": "After depositing, poll 'accounts --agent --chain <chain> --pending-only' while the Pool Account remains pending. Reviewed entries disappear from --pending-only results; once gone, re-run 'accounts --agent --chain <chain>' to confirm whether aspStatus is 'approved', 'declined', or 'poi_required'. Withdraw only after approval; ragequit if declined; complete Proof of Association at tornado.0xbow.io first if poi_required. Always preserve the same --chain scope for both polling and confirmation. Most deposits approve within 1 hour; some may take up to 7 days. Follow nextActions from the deposit response for the canonical polling command.",
    "withdrawQuote": "Use 'withdraw quote <amount> --asset <symbol> --agent' to check relayer fees before committing to a withdrawal.",
    "firstRun": "First proof generation may provision checksum-verified circuit artifacts automatically (~60s one-time). Subsequent proofs are faster (~10-30s).",
    "unsignedMode": "--unsigned builds transaction payloads without signing or submitting. Use --unsigned tx for a raw transaction array (no envelope). Requires init (recovery phrase) for deposit secret generation, but does NOT require a signer key. The 'from' field is null; the signing party fills in their own address.",
    "metaFlag": "--agent is equivalent to --json --yes --quiet. Use it to suppress all stderr output and skip prompts.",
    "statusCheck": "Run 'status --agent' before transacting. readyForDeposit/readyForWithdraw/readyForUnsigned are configuration capability flags; they confirm the wallet is set up, NOT that withdrawable funds exist. Check 'accounts --agent --chain <chain>' to verify fund availability before withdrawing on a specific chain. Use bare 'accounts --agent' only for the default multi-chain mainnet dashboard."
  },
  "schemas": {
    "aspApprovalStatus": {
      "values": [
        "approved",
        "pending",
        "poi_required",
        "declined",
        "unknown"
      ],
      "description": "ASP approval status for a Pool Account. 'approved' means the deposit has been vetted and is eligible for private withdrawal. 'pending' means the ASP has not yet approved the deposit. 'poi_required' means Proof of Association (tornado.0xbow.io) is required before private withdrawal. 'declined' means the ASP rejected the deposit for private withdrawal. 'unknown' applies to exited or spent accounts, or when ASP status could not be determined."
    },
    "poolAccountStatus": {
      "values": [
        "approved",
        "pending",
        "poi_required",
        "declined",
        "unknown",
        "spent",
        "exited"
      ],
      "description": "User-facing status of a Pool Account. Active accounts surface their effective review state ('approved', 'pending', 'poi_required', 'declined', or 'unknown'). 'spent' means an approved account was withdrawn. 'exited' means ragequit/exit was used."
    },
    "errorCategories": {
      "values": [
        "INPUT",
        "RPC",
        "ASP",
        "RELAYER",
        "PROOF",
        "CONTRACT",
        "UNKNOWN"
      ],
      "exitCodes": {
        "INPUT": 2,
        "RPC": 3,
        "ASP": 4,
        "RELAYER": 5,
        "PROOF": 6,
        "CONTRACT": 7,
        "UNKNOWN": 1
      },
      "description": "Error responses include top-level errorCode/errorMessage plus error.{ code, category, message, hint?, retryable? }."
    },
    "unsignedOutput": {
      "envelopeFormat": "{ schemaVersion, success, mode, operation, chain, transactions: [{ to, data, value, ... }], ... }",
      "txFormat": "[{ to, data, value, valueHex, chainId }]: raw array, no envelope wrapper. Intended for direct piping to signing tools.",
      "note": "Default --unsigned emits the envelope format. Use --unsigned tx for raw transaction array only."
    },
    "nextActions": {
      "shape": "{ command, reason, when, args?: string[], options?: Record<string, string|number|boolean|null>, runnable?: boolean }",
      "description": "Canonical workflow guidance for agents. Follow these command suggestions instead of parsing natural-language output. Current nextActions are emitted only when the CLI has a low-ambiguity follow-up to recommend. When runnable is omitted or true, the command is fully specified and can be executed as shown. When runnable is false, the action is a template and requires additional user input before execution."
    }
  },
  "supportedChains": [
    {
      "name": "mainnet",
      "chainId": 1,
      "testnet": false
    },
    {
      "name": "arbitrum",
      "chainId": 42161,
      "testnet": false
    },
    {
      "name": "optimism",
      "chainId": 10,
      "testnet": false
    },
    {
      "name": "sepolia",
      "chainId": 11155111,
      "testnet": true
    },
    {
      "name": "op-sepolia",
      "chainId": 11155420,
      "testnet": true
    }
  ],
  "safeReadOnlyCommands": [
    "flow status",
    "pools",
    "activity",
    "stats",
    "stats global",
    "stats pool",
    "status",
    "capabilities",
    "describe",
    "guide",
    "migrate",
    "migrate status",
    "completion"
  ],
  "jsonOutputContract": "All commands emit { schemaVersion, success, ...payload } on stdout when --json or --agent is set. Errors emit { schemaVersion, success: false, errorCode, errorMessage, error: { code, category, message, hint?, retryable? } }. Exception: --unsigned tx emits a raw transaction array without the envelope.",
  "documentation": {
    "reference": "docs/reference.md",
    "agentGuide": "AGENTS.md",
    "changelog": "CHANGELOG.md"
  }
};

export const STATIC_GLOBAL_FLAG_METADATA = STATIC_CAPABILITIES_PAYLOAD.globalFlags;

export function resolveStaticCommandPath(
  query: string | string[],
): StaticCommandPath | null {
  const normalized = Array.isArray(query)
    ? query.join(" ").trim().replace(/\s+/g, " ")
    : query.trim().replace(/\s+/g, " ");

  if (!normalized) {
    return null;
  }

  if (STATIC_COMMAND_PATH_SET.has(normalized)) {
    return normalized as StaticCommandPath;
  }

  return STATIC_COMMAND_ALIAS_MAP[normalized] ?? null;
}

export function listStaticCommandPaths(): StaticCommandPath[] {
  return [...STATIC_COMMAND_PATHS];
}
