/* AUTO-GENERATED by scripts/generate-command-discovery-static.mjs - DO NOT EDIT */

export type GeneratedCommandOwner = "js-runtime" | "native-shell" | "hybrid";

export interface GeneratedCommandRoute {
  owner: GeneratedCommandOwner;
  nativeModes: readonly string[];
}

export const GENERATED_COMMAND_PATHS = [
  "init",
  "upgrade",
  "config",
  "config list",
  "config get",
  "config set",
  "config unset",
  "config path",
  "config profile",
  "config profile list",
  "config profile create",
  "config profile active",
  "config profile use",
  "flow",
  "simulate",
  "flow start",
  "flow watch",
  "flow status",
  "flow step",
  "flow ragequit",
  "pools",
  "activity",
  "protocol-stats",
  "pool-stats",
  "status",
  "tx-status",
  "capabilities",
  "describe",
  "guide",
  "deposit",
  "withdraw",
  "withdraw quote",
  "ragequit",
  "simulate deposit",
  "simulate withdraw",
  "simulate ragequit",
  "broadcast",
  "accounts",
  "migrate",
  "migrate status",
  "history",
  "sync",
  "completion"
] as const;

export type GeneratedCommandPath = (typeof GENERATED_COMMAND_PATHS)[number];

export interface GeneratedTokenizedCommandRoute {
  route: GeneratedCommandPath;
  tokens: readonly string[];
}

export const GENERATED_STATIC_LOCAL_COMMANDS = [
  "guide",
  "capabilities",
  "describe",
  "completion"
] as const;

export const GENERATED_COMMAND_ALIAS_MAP: Record<string, GeneratedCommandPath> = {
  "remove": "config unset",
  "stats": "protocol-stats",
  "stats global": "protocol-stats",
  "stats pool": "pool-stats",
  "exit": "ragequit"
};

export const GENERATED_COMMAND_ROUTES: Record<GeneratedCommandPath, GeneratedCommandRoute> = {
  "init": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "upgrade": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config list": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config get": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config set": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config unset": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config path": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config profile": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config profile list": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config profile create": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config profile active": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "config profile use": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "simulate": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow start": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow watch": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow status": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow step": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow ragequit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "pools": {
    "owner": "hybrid",
    "nativeModes": [
      "default-list",
      "default-detail",
      "csv-list",
      "structured-list",
      "help"
    ]
  },
  "activity": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "csv",
      "structured",
      "help"
    ]
  },
  "protocol-stats": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "csv",
      "structured",
      "help"
    ]
  },
  "pool-stats": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "csv",
      "structured",
      "help"
    ]
  },
  "status": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "tx-status": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "capabilities": {
    "owner": "native-shell",
    "nativeModes": [
      "default",
      "help"
    ]
  },
  "describe": {
    "owner": "native-shell",
    "nativeModes": [
      "default",
      "help"
    ]
  },
  "guide": {
    "owner": "native-shell",
    "nativeModes": [
      "default",
      "help"
    ]
  },
  "deposit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "withdraw": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "withdraw quote": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "ragequit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "simulate deposit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "simulate withdraw": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "simulate ragequit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "broadcast": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "accounts": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "migrate": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "migrate status": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "history": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "sync": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "completion": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "help"
    ]
  }
};

export const GENERATED_TOKENIZED_COMMAND_ROUTES: readonly GeneratedTokenizedCommandRoute[] = [
  {
    "route": "config profile list",
    "tokens": [
      "config",
      "profile",
      "list"
    ]
  },
  {
    "route": "config profile create",
    "tokens": [
      "config",
      "profile",
      "create"
    ]
  },
  {
    "route": "config profile active",
    "tokens": [
      "config",
      "profile",
      "active"
    ]
  },
  {
    "route": "config profile use",
    "tokens": [
      "config",
      "profile",
      "use"
    ]
  },
  {
    "route": "config list",
    "tokens": [
      "config",
      "list"
    ]
  },
  {
    "route": "config get",
    "tokens": [
      "config",
      "get"
    ]
  },
  {
    "route": "config set",
    "tokens": [
      "config",
      "set"
    ]
  },
  {
    "route": "config unset",
    "tokens": [
      "config",
      "unset"
    ]
  },
  {
    "route": "config path",
    "tokens": [
      "config",
      "path"
    ]
  },
  {
    "route": "config profile",
    "tokens": [
      "config",
      "profile"
    ]
  },
  {
    "route": "flow start",
    "tokens": [
      "flow",
      "start"
    ]
  },
  {
    "route": "flow watch",
    "tokens": [
      "flow",
      "watch"
    ]
  },
  {
    "route": "flow status",
    "tokens": [
      "flow",
      "status"
    ]
  },
  {
    "route": "flow step",
    "tokens": [
      "flow",
      "step"
    ]
  },
  {
    "route": "flow ragequit",
    "tokens": [
      "flow",
      "ragequit"
    ]
  },
  {
    "route": "withdraw quote",
    "tokens": [
      "withdraw",
      "quote"
    ]
  },
  {
    "route": "simulate deposit",
    "tokens": [
      "simulate",
      "deposit"
    ]
  },
  {
    "route": "simulate withdraw",
    "tokens": [
      "simulate",
      "withdraw"
    ]
  },
  {
    "route": "simulate ragequit",
    "tokens": [
      "simulate",
      "ragequit"
    ]
  },
  {
    "route": "migrate status",
    "tokens": [
      "migrate",
      "status"
    ]
  },
  {
    "route": "init",
    "tokens": [
      "init"
    ]
  },
  {
    "route": "upgrade",
    "tokens": [
      "upgrade"
    ]
  },
  {
    "route": "config",
    "tokens": [
      "config"
    ]
  },
  {
    "route": "flow",
    "tokens": [
      "flow"
    ]
  },
  {
    "route": "simulate",
    "tokens": [
      "simulate"
    ]
  },
  {
    "route": "pools",
    "tokens": [
      "pools"
    ]
  },
  {
    "route": "activity",
    "tokens": [
      "activity"
    ]
  },
  {
    "route": "protocol-stats",
    "tokens": [
      "protocol-stats"
    ]
  },
  {
    "route": "pool-stats",
    "tokens": [
      "pool-stats"
    ]
  },
  {
    "route": "status",
    "tokens": [
      "status"
    ]
  },
  {
    "route": "tx-status",
    "tokens": [
      "tx-status"
    ]
  },
  {
    "route": "capabilities",
    "tokens": [
      "capabilities"
    ]
  },
  {
    "route": "describe",
    "tokens": [
      "describe"
    ]
  },
  {
    "route": "guide",
    "tokens": [
      "guide"
    ]
  },
  {
    "route": "deposit",
    "tokens": [
      "deposit"
    ]
  },
  {
    "route": "withdraw",
    "tokens": [
      "withdraw"
    ]
  },
  {
    "route": "ragequit",
    "tokens": [
      "ragequit"
    ]
  },
  {
    "route": "broadcast",
    "tokens": [
      "broadcast"
    ]
  },
  {
    "route": "accounts",
    "tokens": [
      "accounts"
    ]
  },
  {
    "route": "migrate",
    "tokens": [
      "migrate"
    ]
  },
  {
    "route": "history",
    "tokens": [
      "history"
    ]
  },
  {
    "route": "sync",
    "tokens": [
      "sync"
    ]
  },
  {
    "route": "completion",
    "tokens": [
      "completion"
    ]
  }
] as const;
