/* AUTO-GENERATED by scripts/generate-command-discovery-static.mjs - DO NOT EDIT */

import type { CapabilitiesPayload } from "../types.js";

export type GeneratedCommandOwner = "js-runtime" | "native-shell" | "hybrid";

export interface GeneratedCommandRoute {
  owner: GeneratedCommandOwner;
  nativeModes: readonly string[];
}

export const GENERATED_COMMAND_PATHS = [
  "init",
  "upgrade",
  "flow",
  "flow start",
  "flow watch",
  "flow status",
  "flow ragequit",
  "pools",
  "activity",
  "stats",
  "stats global",
  "stats pool",
  "status",
  "capabilities",
  "describe",
  "guide",
  "deposit",
  "withdraw",
  "withdraw quote",
  "ragequit",
  "accounts",
  "migrate",
  "migrate status",
  "history",
  "sync",
  "completion"
] as const;

export type GeneratedCommandPath = (typeof GENERATED_COMMAND_PATHS)[number];

export const GENERATED_ROOT_COMMANDS = [
  {
    "name": "init",
    "aliases": [],
    "description": "Initialize wallet and configuration"
  },
  {
    "name": "upgrade",
    "aliases": [],
    "description": "Check npm for updates or upgrade this CLI"
  },
  {
    "name": "flow",
    "aliases": [],
    "description": "Guided deposit-to-private-withdrawal workflow"
  },
  {
    "name": "pools",
    "aliases": [],
    "description": "List available pools and assets"
  },
  {
    "name": "activity",
    "aliases": [],
    "description": "Show public activity feed"
  },
  {
    "name": "stats",
    "aliases": [],
    "description": "Show public statistics"
  },
  {
    "name": "status",
    "aliases": [],
    "description": "Show configuration and check connection health"
  },
  {
    "name": "capabilities",
    "aliases": [],
    "description": "Describe CLI capabilities for agent discovery"
  },
  {
    "name": "describe",
    "aliases": [],
    "description": "Describe one command for runtime agent introspection"
  },
  {
    "name": "guide",
    "aliases": [],
    "description": "Show usage guide, workflow, and reference"
  },
  {
    "name": "deposit",
    "aliases": [],
    "description": "Deposit funds into a Privacy Pool"
  },
  {
    "name": "withdraw",
    "aliases": [],
    "description": "Privately withdraw funds via relayer"
  },
  {
    "name": "ragequit",
    "aliases": [
      "exit"
    ],
    "description": "Publicly withdraw funds to your deposit address"
  },
  {
    "name": "accounts",
    "aliases": [],
    "description": "List your Pool Accounts (individual deposit lineages) with balances"
  },
  {
    "name": "migrate",
    "aliases": [],
    "description": "Inspect legacy migration readiness on CLI-supported chains"
  },
  {
    "name": "history",
    "aliases": [],
    "description": "Show chronological event history (deposits, migrations, withdrawals, ragequits)"
  },
  {
    "name": "sync",
    "aliases": [],
    "description": "Force-sync local account state from onchain events"
  },
  {
    "name": "completion",
    "aliases": [],
    "description": "Generate shell completion script"
  }
] as const;

export const GENERATED_STATIC_LOCAL_COMMANDS = [
  "guide",
  "capabilities",
  "describe",
  "completion"
] as const;

export const GENERATED_COMMAND_ALIAS_MAP: Record<string, GeneratedCommandPath> = {
  "exit": "ragequit"
};

export const GENERATED_COMMAND_ROUTES: Record<GeneratedCommandPath, GeneratedCommandRoute> = {
  "init": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "upgrade": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow start": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow watch": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow status": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "flow ragequit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "pools": {
    "owner": "hybrid",
    "nativeModes": [
      "default-list",
      "csv-list",
      "structured-list",
      "help"
    ]
  },
  "activity": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "csv",
      "structured",
      "help"
    ]
  },
  "stats": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "csv",
      "structured-default",
      "structured-global",
      "help"
    ]
  },
  "stats global": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "csv",
      "structured",
      "help"
    ]
  },
  "stats pool": {
    "owner": "hybrid",
    "nativeModes": [
      "default",
      "csv",
      "structured",
      "help"
    ]
  },
  "status": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "capabilities": {
    "owner": "native-shell",
    "nativeModes": [
      "default",
      "help"
    ]
  },
  "describe": {
    "owner": "native-shell",
    "nativeModes": [
      "default",
      "help"
    ]
  },
  "guide": {
    "owner": "native-shell",
    "nativeModes": [
      "default",
      "help"
    ]
  },
  "deposit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "withdraw": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "withdraw quote": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "ragequit": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "accounts": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "migrate": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "migrate status": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "history": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "sync": {
    "owner": "js-runtime",
    "nativeModes": [
      "help"
    ]
  },
  "completion": {
    "owner": "native-shell",
    "nativeModes": [
      "default",
      "help"
    ]
  }
};

export const GENERATED_CAPABILITIES_PAYLOAD: CapabilitiesPayload = {
  "commands": [
    {
      "name": "init",
      "description": "Initialize wallet and configuration",
      "usage": "init",
      "flags": [
        "--mnemonic <phrase>",
        "--mnemonic-file <path>",
        "--mnemonic-stdin",
        "--private-key <key>",
        "--private-key-file <path>",
        "--private-key-stdin",
        "--default-chain <chain>",
        "--force",
        "--show-mnemonic"
      ],
      "agentFlags": "--agent --default-chain <chain> --show-mnemonic",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "upgrade",
      "description": "Check npm for updates or upgrade this CLI",
      "usage": "upgrade",
      "flags": [
        "--check"
      ],
      "agentFlags": "--agent [--check] [--yes]",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "flow",
      "description": "Guided deposit-to-private-withdrawal workflow",
      "usage": "flow",
      "flags": [
        "start <amount> <asset> --to <address>",
        "watch [workflowId|latest]",
        "status [workflowId|latest]",
        "ragequit [workflowId|latest]"
      ],
      "agentFlags": "start <amount> <asset> --to <address> [--privacy-delay <profile>] --agent (or: watch [workflowId|latest] [--privacy-delay <profile>] --agent; status/ragequit --agent)",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "flow start",
      "description": "Deposit now and save a later private withdrawal workflow",
      "usage": "flow start <amount> <asset> --to <address>",
      "flags": [
        "--to <address>",
        "--privacy-delay <profile>",
        "--watch",
        "--new-wallet",
        "--export-new-wallet <path>"
      ],
      "agentFlags": "--agent [--privacy-delay <profile>] [--watch] [--new-wallet] [--export-new-wallet <path>]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "flow watch",
      "description": "Resume a saved flow through funding, approval, privacy delay, and withdrawal",
      "usage": "flow watch [workflowId|latest]",
      "flags": [
        "[workflowId|latest]",
        "--privacy-delay <profile>"
      ],
      "agentFlags": "--agent [--privacy-delay <profile>]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "flow status",
      "description": "Show the saved easy-path workflow state",
      "usage": "flow status [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "flow ragequit",
      "description": "Recover a saved workflow publicly via ragequit",
      "usage": "flow ragequit [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "pools",
      "description": "List available pools and assets",
      "usage": "pools",
      "flags": [
        "--all-chains",
        "--search <query>",
        "--sort <mode>"
      ],
      "agentFlags": "--agent [--all-chains] [--search <query>] [--sort <mode>]",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "activity",
      "description": "Show public activity feed",
      "usage": "activity",
      "flags": [
        "--asset <symbol|address>",
        "--page <n>",
        "--limit <n>"
      ],
      "agentFlags": "--agent [--asset <symbol>] [--page <n>] [--limit <n>]",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "stats",
      "description": "Show public statistics",
      "usage": "stats",
      "flags": [
        "global",
        "pool --asset <symbol|address>"
      ],
      "agentFlags": "global --agent (or: pool --asset <symbol> --agent)",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "stats global",
      "description": "Show global Privacy Pools statistics (all-time and last 24h)",
      "usage": "stats global",
      "flags": [],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "stats pool",
      "description": "Show statistics for a specific pool (all-time and last 24h)",
      "usage": "stats pool --asset <symbol|address>",
      "flags": [
        "--asset <symbol|address>"
      ],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "describe",
      "description": "Describe one command for runtime agent introspection",
      "usage": "describe <command...>",
      "flags": [
        "<command...>"
      ],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "deposit",
      "description": "Deposit funds into a Privacy Pool",
      "usage": "deposit <amount> [asset]",
      "flags": [
        "--asset <symbol|address>",
        "--unsigned [envelope|tx]",
        "--dry-run",
        "--ignore-unique-amount"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "withdraw",
      "description": "Privately withdraw funds via relayer",
      "usage": "withdraw [amount] [asset] --to <address>",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>",
        "--from-pa <PA-#>",
        "--all",
        "--direct",
        "--extra-gas",
        "--no-extra-gas",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "withdraw quote",
      "description": "Request relayer quote and limits without generating a proof",
      "usage": "withdraw quote <amount> --asset <symbol|address>",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "medium"
    },
    {
      "name": "accounts",
      "description": "List your Pool Accounts (individual deposit lineages) with balances",
      "usage": "accounts",
      "flags": [
        "--no-sync",
        "--all-chains",
        "--details",
        "--summary",
        "--pending-only"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "migrate",
      "description": "Inspect legacy migration readiness on CLI-supported chains",
      "usage": "migrate",
      "flags": [
        "status [--all-chains]"
      ],
      "agentFlags": "status --agent [--all-chains]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "migrate status",
      "description": "Show legacy migration readiness on CLI-supported chains",
      "usage": "migrate status",
      "flags": [
        "--all-chains"
      ],
      "agentFlags": "--agent [--all-chains]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "history",
      "description": "Show chronological event history (deposits, migrations, withdrawals, ragequits)",
      "usage": "history",
      "flags": [
        "--no-sync",
        "--limit <n>"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "sync",
      "description": "Force-sync local account state from onchain events",
      "usage": "sync",
      "flags": [
        "-a, --asset <symbol|address>"
      ],
      "agentFlags": "--agent [--asset <symbol>]",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "status",
      "description": "Show configuration and check connection health",
      "usage": "status",
      "flags": [
        "--check",
        "--no-check",
        "--check-rpc",
        "--check-asp"
      ],
      "agentFlags": "--agent [--no-check] [--check-rpc] [--check-asp]",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "ragequit",
      "description": "Publicly withdraw funds to your deposit address",
      "aliases": [
        "exit"
      ],
      "usage": "ragequit [asset] --from-pa <PA-#>",
      "flags": [
        "--asset <symbol|address>",
        "--from-pa <PA-#>",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "agentFlags": "--agent",
      "requiresInit": true,
      "expectedLatencyClass": "slow"
    },
    {
      "name": "guide",
      "description": "Show usage guide, workflow, and reference",
      "usage": "guide",
      "flags": [],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "completion",
      "description": "Generate shell completion script",
      "usage": "completion",
      "flags": [
        "[shell]",
        "--shell <shell>"
      ],
      "agentFlags": "--agent <shell>",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    },
    {
      "name": "capabilities",
      "description": "Describe CLI capabilities for agent discovery",
      "usage": "capabilities",
      "flags": [],
      "agentFlags": "--agent",
      "requiresInit": false,
      "expectedLatencyClass": "fast"
    }
  ],
  "commandDetails": {
    "init": {
      "command": "init",
      "description": "Initialize wallet and configuration",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "init",
      "flags": [
        "--mnemonic <phrase>",
        "--mnemonic-file <path>",
        "--mnemonic-stdin",
        "--private-key <key>",
        "--private-key-file <path>",
        "--private-key-stdin",
        "--default-chain <chain>",
        "--force",
        "--show-mnemonic"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": false,
      "sideEffectClass": "local_state_write",
      "touchesFunds": false,
      "requiresHumanReview": true,
      "prerequisites": [],
      "examples": [
        "privacy-pools init",
        "privacy-pools init --yes --default-chain mainnet",
        "privacy-pools init --force --yes --default-chain mainnet",
        "privacy-pools init --agent --default-chain mainnet --show-mnemonic",
        "privacy-pools init --mnemonic-file ./my-mnemonic.txt --private-key-file ./my-key.txt",
        "cat phrase.txt | privacy-pools init --mnemonic-stdin --yes --default-chain mainnet",
        "printf '%s\\n' 0x... | privacy-pools init --mnemonic-file ./my-mnemonic.txt --private-key-stdin --yes --default-chain mainnet"
      ],
      "jsonFields": "{ defaultChain, signerKeySet, recoveryPhraseRedacted? | recoveryPhrase?, warning?, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
      "jsonVariants": [],
      "safetyNotes": [
        "The recovery phrase and signer key are independent secrets: the phrase controls deposit privacy, the key pays gas. Neither is derived from the other.",
        "Newly generated recovery phrases use 24 words (256-bit entropy). Imported recovery phrases may still be 12 or 24 words.",
        "Legacy pre-upgrade accounts may need website migration or website-based recovery before the CLI can safely restore them."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "When generating a new recovery phrase in machine mode, pass --show-mnemonic and capture it immediately.",
        "When importing an existing recovery phrase, nextActions points to migrate status --agent --all-chains first so the CLI can check legacy migration or website-recovery readiness before restoring account state."
      ]
    },
    "upgrade": {
      "command": "upgrade",
      "description": "Check npm for updates or upgrade this CLI",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "upgrade",
      "flags": [
        "--check"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": false,
      "sideEffectClass": "local_state_write",
      "touchesFunds": false,
      "requiresHumanReview": true,
      "preferredSafeVariant": {
        "command": "upgrade --check",
        "reason": "Check for a newer npm release without mutating the installed CLI."
      },
      "prerequisites": [],
      "examples": [
        "privacy-pools upgrade --check",
        "privacy-pools upgrade",
        "privacy-pools upgrade --yes",
        "privacy-pools upgrade --agent --check",
        "privacy-pools upgrade --agent --yes"
      ],
      "jsonFields": "{ mode: \"upgrade\", status, currentVersion, latestVersion, updateAvailable, performed, command|null, installContext: { kind, supportedAutoRun, reason }, installedVersion|null }",
      "jsonVariants": [],
      "safetyNotes": [
        "Automatic upgrade only runs for recognized global npm installs of privacy-pools-cli.",
        "Source checkouts, non-npm global installs, local project installs, npx-style ephemeral runs, CI, and ambiguous contexts stay read-only and still return an exact npm follow-up command.",
        "A successful upgrade updates the installed CLI on disk but does not hot-reexec the current process. Re-run privacy-pools after it completes."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "In machine modes, upgrade is check-only unless --yes is explicitly present.",
        "Treat status = ready as an available update on a supported global npm install, status = manual as an available update requiring manual follow-up, and status = upgraded as a completed install that still requires a fresh CLI invocation."
      ]
    },
    "flow": {
      "command": "flow",
      "description": "Guided deposit-to-private-withdrawal workflow",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "flow",
      "flags": [
        "start <amount> <asset> --to <address>",
        "watch [workflowId|latest]",
        "status [workflowId|latest]",
        "ragequit [workflowId|latest]"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "init for start/watch/ragequit; saved workflow for status"
      ],
      "examples": [
        "privacy-pools flow start 0.1 ETH --to 0xRecipient...",
        "privacy-pools flow start 0.1 ETH --to 0xRecipient... --watch",
        "privacy-pools flow start 100 USDC --to 0xRecipient... --new-wallet --export-new-wallet ./flow-wallet.txt",
        "privacy-pools flow watch",
        "privacy-pools flow status latest",
        "privacy-pools flow ragequit latest"
      ],
      "jsonFields": null,
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "flow start": {
      "command": "flow start",
      "description": "Deposit now and save a later private withdrawal workflow",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "flow start <amount> <asset> --to <address>",
      "flags": [
        "--to <address>",
        "--privacy-delay <profile>",
        "--watch",
        "--new-wallet",
        "--export-new-wallet <path>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "fund_movement",
      "touchesFunds": true,
      "requiresHumanReview": true,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools flow start 0.1 ETH --to 0xRecipient...",
        "privacy-pools flow start 0.1 ETH --to 0xRecipient... --privacy-delay off",
        "privacy-pools flow start 100 USDC --to 0xRecipient... --chain mainnet",
        "privacy-pools flow start 100 USDC --to 0xRecipient... --new-wallet --export-new-wallet ./flow-wallet.txt",
        "privacy-pools flow start 0.1 ETH --to 0xRecipient... --watch --agent"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"start\", workflowId, phase, walletMode, walletAddress|null, requiredNativeFunding|null, requiredTokenFunding|null, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId|null, poolAccountNumber|null, depositTxHash|null, depositBlockNumber|null, depositExplorerUrl|null, committedValue|null, aspStatus?, privacyDelayProfile, privacyDelayConfigured, privacyDelayUntil|null, withdrawTxHash|null, withdrawBlockNumber|null, withdrawExplorerUrl|null, ragequitTxHash|null, ragequitBlockNumber|null, ragequitExplorerUrl|null, warnings?: [{ code, category: \"privacy\", message }], lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [
        "The deposit is still public and reviewed by the ASP before private withdrawal is possible.",
        "If --to is omitted in interactive mode, the CLI prompts for the recipient. In machine modes, --to remains required.",
        "In machine modes, non-round flow amounts are rejected. Use a round amount in agent/non-interactive runs, or switch to interactive mode if you intentionally accept that tradeoff.",
        "New workflows default to a balanced post-approval privacy delay before relayed withdrawal. off = no added hold, balanced = randomized 15 to 90 minutes, aggressive = randomized 2 to 12 hours.",
        "Vetting fees can turn a round deposit input into a non-round committed balance, so flow start may still emit an advisory amount-pattern warning for the later full-balance auto-withdrawal.",
        "flow start surfaces advisory privacy warnings when the saved workflow is configured to auto-withdraw a full non-round balance, or when timing delay is explicitly disabled.",
        "--export-new-wallet is only valid with --new-wallet.",
        "Non-interactive workflow wallets require --export-new-wallet so the generated private key is backed up before the flow starts.",
        "The generated workflow key is also stored locally under workflow-secrets until the workflow completes or recovers publicly, so --export-new-wallet is a backup copy rather than the only retained secret.",
        "Dedicated workflow wallets may retain leftover asset balance or gas reserve after paused or terminal states, so check them manually before assuming they are empty.",
        "The saved flow spends the entire remaining Pool Account balance, but the recipient receives the net amount after relayer fees and any ERC20 extra-gas funding.",
        "Manual commands remain the advanced/manual path when you need custom control over Pool Account selection, amount, or withdrawal mode."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "With --new-wallet, the flow stays attached automatically and waits for funding, deposit, approval, and withdrawal unless you detach with Ctrl-C.",
        "Use --watch to stay attached on configured-wallet workflows; otherwise the workflow is persisted locally and flow watch <workflowId> is the canonical resume path."
      ]
    },
    "flow watch": {
      "command": "flow watch",
      "description": "Resume a saved flow through funding, approval, privacy delay, and withdrawal",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "flow watch [workflowId|latest]",
      "flags": [
        "[workflowId|latest]",
        "--privacy-delay <profile>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "fund_movement",
      "touchesFunds": true,
      "requiresHumanReview": true,
      "preferredSafeVariant": {
        "command": "flow status",
        "reason": "Inspect the saved workflow state before re-attaching a long-running flow."
      },
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools flow watch",
        "privacy-pools flow watch latest --privacy-delay off   # updates the saved privacy-delay policy",
        "privacy-pools flow watch latest --agent",
        "privacy-pools flow watch 123e4567-e89b-12d3-a456-426614174000"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"watch\", workflowId, phase, walletMode, walletAddress|null, requiredNativeFunding|null, requiredTokenFunding|null, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId|null, poolAccountNumber|null, depositTxHash|null, depositBlockNumber|null, depositExplorerUrl|null, committedValue|null, aspStatus?, privacyDelayProfile, privacyDelayConfigured, privacyDelayUntil|null, withdrawTxHash|null, withdrawBlockNumber|null, withdrawExplorerUrl|null, ragequitTxHash|null, ragequitBlockNumber|null, ragequitExplorerUrl|null, warnings?: [{ code, category: \"privacy\", message }], lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [
        "Paused states are successful workflow states, not CLI errors. Declined workflows surface flow ragequit as the canonical public recovery path, and PoA-required workflows can either resume privately after the external Proof of Association step or recover publicly with flow ragequit.",
        "If the saved full-balance withdrawal falls below the relayer minimum, flow watch surfaces flow ragequit as the required public recovery path because saved flows only support relayed private withdrawals.",
        "Once the public deposit exists, operators can also choose flow ragequit manually instead of waiting, but it is not emitted as the default nextAction while the workflow is still progressing normally. The happy-path canonical resume command remains flow watch.",
        "Passing --privacy-delay on flow watch updates the saved workflow policy. off = no added hold, balanced = randomized 15 to 90 minutes, aggressive = randomized 2 to 12 hours.",
        "Switching to off clears any saved hold immediately; switching between balanced and aggressive resamples from the override time."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "New-wallet workflows wait for funding automatically. ERC20 workflows require both the token amount and a native ETH gas reserve in the generated wallet before the public deposit can proceed.",
        "When the saved Pool Account is approved, flow watch performs the relayed private withdrawal automatically using the saved recipient and the full remaining balance of that same Pool Account after any configured privacy delay hold expires.",
        "flow watch keeps polling until the saved workflow changes or finishes. If your automation should stop after a fixed duration, wrap the CLI call in your own external timeout."
      ]
    },
    "flow status": {
      "command": "flow status",
      "description": "Show the saved easy-path workflow state",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "flow status [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "saved workflow (usually created after init)"
      ],
      "examples": [
        "privacy-pools flow status",
        "privacy-pools flow status latest --agent",
        "privacy-pools flow status 123e4567-e89b-12d3-a456-426614174000"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"status\", workflowId, phase, walletMode, walletAddress|null, requiredNativeFunding|null, requiredTokenFunding|null, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId|null, poolAccountNumber|null, depositTxHash|null, depositBlockNumber|null, depositExplorerUrl|null, committedValue|null, aspStatus?, privacyDelayProfile, privacyDelayConfigured, privacyDelayUntil|null, withdrawTxHash|null, withdrawBlockNumber|null, withdrawExplorerUrl|null, ragequitTxHash|null, ragequitBlockNumber|null, ragequitExplorerUrl|null, warnings?: [{ code, category: \"privacy\", message }], lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "flow ragequit": {
      "command": "flow ragequit",
      "description": "Recover a saved workflow publicly via ragequit",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "flow ragequit [workflowId|latest]",
      "flags": [
        "[workflowId|latest]"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "fund_movement",
      "touchesFunds": true,
      "requiresHumanReview": true,
      "preferredSafeVariant": {
        "command": "flow status",
        "reason": "Inspect the saved workflow state before triggering the public recovery path."
      },
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools flow ragequit",
        "privacy-pools flow ragequit latest --agent",
        "privacy-pools flow ragequit 123e4567-e89b-12d3-a456-426614174000"
      ],
      "jsonFields": "{ mode: \"flow\", action: \"ragequit\", workflowId, phase, walletMode, walletAddress|null, requiredNativeFunding|null, requiredTokenFunding|null, backupConfirmed?, chain, asset, depositAmount, recipient, poolAccountId|null, poolAccountNumber|null, depositTxHash|null, depositBlockNumber|null, depositExplorerUrl|null, committedValue|null, aspStatus?, privacyDelayProfile, privacyDelayConfigured, privacyDelayUntil|null, withdrawTxHash|null, withdrawBlockNumber|null, withdrawExplorerUrl|null, ragequitTxHash|null, ragequitBlockNumber|null, ragequitExplorerUrl|null, lastError?, nextActions? }",
      "jsonVariants": [],
      "safetyNotes": [
        "This is a public recovery path. It exits to the original deposit address and does not preserve privacy.",
        "Configured-wallet recovery only works when the current signer still matches the original depositor address saved with the workflow."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "pools": {
      "command": "pools",
      "description": "List available pools and assets",
      "aliases": [],
      "execution": {
        "owner": "hybrid",
        "nativeModes": [
          "default-list",
          "csv-list",
          "structured-list",
          "help"
        ]
      },
      "usage": "pools",
      "flags": [
        "--all-chains",
        "--search <query>",
        "--sort <mode>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools pools",
        "privacy-pools pools ETH",
        "privacy-pools pools BOLD --chain mainnet",
        "privacy-pools pools --all-chains --sort tvl-desc",
        "privacy-pools pools --search usdc --sort asset-asc",
        "privacy-pools pools --agent --chain mainnet"
      ],
      "jsonFields": "{ chain?, allChains?, chains?, search, sort, pools: [{ chain?, asset, tokenAddress, pool, scope, totalDepositsCount, totalDepositsValue, acceptedDepositsValue, pendingDepositsValue, ... }], warnings? }",
      "jsonVariants": [
        "detail (<asset>): { chain, asset, tokenAddress, pool, scope, ..., myFunds?, myFundsWarning?, recentActivity? }",
        "detail myFunds: { balance, usdValue, poolAccounts, pendingCount, poiRequiredCount, declinedCount, accounts: [{ id, status, aspStatus, value }] }"
      ],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "In pools JSON, 'asset' is the symbol for CLI follow-up commands and 'tokenAddress' is the contract address."
      ]
    },
    "activity": {
      "command": "activity",
      "description": "Show public activity feed",
      "aliases": [],
      "execution": {
        "owner": "hybrid",
        "nativeModes": [
          "default",
          "csv",
          "structured",
          "help"
        ]
      },
      "usage": "activity",
      "flags": [
        "--asset <symbol|address>",
        "--page <n>",
        "--limit <n>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools activity",
        "privacy-pools activity --page 2 --limit 20",
        "privacy-pools activity --asset ETH",
        "privacy-pools activity --asset USDC --agent --chain mainnet"
      ],
      "jsonFields": "{ mode, chain, chains?, page, perPage, total, totalPages, chainFiltered?, note?, asset?, pool?, scope?, events: [{ type, txHash, explorerUrl, reviewStatus, amountRaw, amountFormatted, poolSymbol, poolAddress, chainId, timestamp }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "stats": {
      "command": "stats",
      "description": "Show public statistics",
      "aliases": [],
      "execution": {
        "owner": "hybrid",
        "nativeModes": [
          "default",
          "csv",
          "structured-default",
          "structured-global",
          "help"
        ]
      },
      "usage": "stats",
      "flags": [
        "global",
        "pool --asset <symbol|address>"
      ],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools stats global",
        "privacy-pools stats pool --asset ETH",
        "privacy-pools stats pool --asset USDC --agent --chain mainnet"
      ],
      "jsonFields": null,
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "stats global": {
      "command": "stats global",
      "description": "Show global Privacy Pools statistics (all-time and last 24h)",
      "aliases": [],
      "execution": {
        "owner": "hybrid",
        "nativeModes": [
          "default",
          "csv",
          "structured",
          "help"
        ]
      },
      "usage": "stats global",
      "flags": [],
      "globalFlags": [
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools stats global",
        "privacy-pools stats global --agent"
      ],
      "jsonFields": "{ mode, chain, chains?, cacheTimestamp?, allTime?, last24h?, perChain?: [{ chain, cacheTimestamp, allTime, last24h }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "stats pool": {
      "command": "stats pool",
      "description": "Show statistics for a specific pool (all-time and last 24h)",
      "aliases": [],
      "execution": {
        "owner": "hybrid",
        "nativeModes": [
          "default",
          "csv",
          "structured",
          "help"
        ]
      },
      "usage": "stats pool --asset <symbol|address>",
      "flags": [
        "--asset <symbol|address>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "medium",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools stats pool --asset ETH",
        "privacy-pools stats pool --asset USDC --agent --chain mainnet"
      ],
      "jsonFields": "{ mode, chain, asset, pool, scope, cacheTimestamp?, allTime?, last24h? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "status": {
      "command": "status",
      "description": "Show configuration and check connection health",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "status",
      "flags": [
        "--check",
        "--no-check",
        "--check-rpc",
        "--check-asp"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools status",
        "privacy-pools status --check",
        "privacy-pools status --no-check",
        "privacy-pools status --agent --check-rpc",
        "privacy-pools status --chain mainnet --rpc-url https://..."
      ],
      "jsonFields": "{ configExists, configDir, defaultChain, selectedChain, rpcUrl, rpcIsCustom, recoveryPhraseSet, signerKeySet, signerKeyValid, signerAddress, signerBalance?, signerBalanceDecimals?, signerBalanceSymbol?, entrypoint, aspHost, accountFiles: [{ chain, chainId }], readyForDeposit, readyForWithdraw, readyForUnsigned, recommendedMode, blockingIssues?, warnings?, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }], aspLive?, rpcLive?, rpcBlockNumber? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "capabilities": {
      "command": "capabilities",
      "description": "Describe CLI capabilities for agent discovery",
      "aliases": [],
      "execution": {
        "owner": "native-shell",
        "nativeModes": [
          "default",
          "help"
        ]
      },
      "usage": "capabilities",
      "flags": [],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools capabilities",
        "privacy-pools capabilities --agent"
      ],
      "jsonFields": "{ commands[], commandDetails{}, executionRoutes{}, globalFlags[], agentWorkflow[], agentNotes{}, schemas{}, supportedChains[], protocol{}, runtime{}, safeReadOnlyCommands[], jsonOutputContract, documentation?: { reference, agentGuide, changelog, runtimeUpgrades, jsonContract } }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "describe": {
      "command": "describe",
      "description": "Describe one command for runtime agent introspection",
      "aliases": [],
      "execution": {
        "owner": "native-shell",
        "nativeModes": [
          "default",
          "help"
        ]
      },
      "usage": "describe <command...>",
      "flags": [
        "<command...>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools describe withdraw",
        "privacy-pools describe withdraw quote --agent",
        "privacy-pools describe stats global --agent"
      ],
      "jsonFields": "{ command, description, aliases, usage, flags, globalFlags, requiresInit, expectedLatencyClass, safeReadOnly, sideEffectClass, touchesFunds, requiresHumanReview, preferredSafeVariant?, prerequisites, examples, jsonFields, jsonVariants, safetyNotes, supportsUnsigned, supportsDryRun, agentWorkflowNotes }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "guide": {
      "command": "guide",
      "description": "Show usage guide, workflow, and reference",
      "aliases": [],
      "execution": {
        "owner": "native-shell",
        "nativeModes": [
          "default",
          "help"
        ]
      },
      "usage": "guide",
      "flags": [],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools guide",
        "privacy-pools guide --agent"
      ],
      "jsonFields": "{ mode: \"help\", help }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "deposit": {
      "command": "deposit",
      "description": "Deposit funds into a Privacy Pool",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "deposit <amount> [asset]",
      "flags": [
        "--asset <symbol|address>",
        "--unsigned [envelope|tx]",
        "--dry-run",
        "--ignore-unique-amount"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "fund_movement",
      "touchesFunds": true,
      "requiresHumanReview": true,
      "preferredSafeVariant": {
        "command": "pools",
        "reason": "Browse pools and balances before submitting a new deposit."
      },
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools deposit 0.1 ETH",
        "privacy-pools deposit 100 USDC",
        "privacy-pools deposit 0.05 ETH --agent",
        "privacy-pools deposit 0.1 ETH --unsigned",
        "privacy-pools deposit 0.1 ETH --dry-run",
        "privacy-pools deposit 0.1 --asset ETH --chain mainnet"
      ],
      "jsonFields": "{ operation, txHash, amount, committedValue, asset, chain, poolAccountNumber, poolAccountId, poolAddress, scope, label, blockNumber, explorerUrl, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
      "jsonVariants": [
        "--unsigned: { mode, operation, chain, asset, amount, precommitment, transactions[] }",
        "--unsigned tx: [{ from, to, data, value, valueHex, chainId, description }]",
        "--dry-run: { dryRun, operation, chain, asset, amount, poolAccountNumber, poolAccountId, precommitment, balanceSufficient }"
      ],
      "safetyNotes": [
        "Deposits are reviewed by the ASP before approval. Most deposits are approved within 1 hour, but some may take longer (up to 7 days).",
        "A vetting fee is deducted from the deposit amount by the pool's ASP.",
        "Only approved deposits can use withdraw, whether relayed or direct. Declined deposits must use ragequit publicly. Deposits that require Proof of Association (PoA) must complete the PoA flow at tornado.0xbow.io before they can withdraw privately."
      ],
      "supportsUnsigned": true,
      "supportsDryRun": true,
      "agentWorkflowNotes": [
        "Poll accounts --chain <chain> --pending-only while the Pool Account remains pending; when it disappears from pending results, re-run accounts --chain <chain> to confirm whether aspStatus became approved, declined, or requires Proof of Association. Withdraw only after approval; ragequit if declined; complete Proof of Association at tornado.0xbow.io first if needed. Always preserve the same --chain scope for both polling and confirmation.",
        "If the deposit transaction was submitted but confirmation timed out or the CLI was interrupted afterward, run sync --chain <chain> before retrying so local state can reconcile the onchain deposit."
      ]
    },
    "withdraw": {
      "command": "withdraw",
      "description": "Privately withdraw funds via relayer",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "withdraw [amount] [asset] --to <address>",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>",
        "--from-pa <PA-#>",
        "--all",
        "--direct",
        "--extra-gas",
        "--no-extra-gas",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "fund_movement",
      "touchesFunds": true,
      "requiresHumanReview": true,
      "preferredSafeVariant": {
        "command": "withdraw quote",
        "reason": "Check relayer fees and confirm the withdrawal inputs before submitting."
      },
      "prerequisites": [
        "init (account state should be synced)"
      ],
      "examples": [
        "privacy-pools withdraw 0.05 ETH --to 0xRecipient...",
        "privacy-pools withdraw 0.05 ETH --to 0xRecipient... --from-pa PA-2",
        "privacy-pools withdraw --all ETH --to 0xRecipient...",
        "privacy-pools withdraw 50% ETH --to 0xRecipient...",
        "privacy-pools withdraw 0.1 ETH --to 0xRecipient... --dry-run",
        "privacy-pools withdraw quote 0.1 ETH --to 0xRecipient...",
        "privacy-pools withdraw 0.05 ETH --to 0xRecipient... --chain mainnet"
      ],
      "jsonFields": "{ operation, mode, txHash, blockNumber, amount, recipient, explorerUrl, poolAddress, scope, asset, chain, poolAccountNumber, poolAccountId, feeBPS, extraGas?, remainingBalance, anonymitySet?: { eligible, total, percentage }, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
      "jsonVariants": [
        "direct: same fields but mode: \"direct\", feeBPS: null, no extraGas, and human output explains the onchain link between deposit and withdrawal.",
        "quote: { mode: \"relayed-quote\", chain, asset, amount, recipient, minWithdrawAmount, minWithdrawAmountFormatted, baseFeeBPS, quoteFeeBPS, feeAmount, netAmount, feeCommitmentPresent, quoteExpiresAt, relayTxCost, extraGas?, extraGasFundAmount?, extraGasTxCost?, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
        "--unsigned: { mode, operation, withdrawMode, chain, transactions[], ... }",
        "--unsigned tx: [{ from, to, data, value, valueHex, chainId, description }]",
        "--dry-run: { operation, mode, dryRun, amount, asset, chain, recipient, poolAccountNumber, poolAccountId, selectedCommitmentLabel, selectedCommitmentValue, proofPublicSignals, feeBPS?, quoteExpiresAt?, extraGas?, anonymitySet?: { eligible, total, percentage } }"
      ],
      "safetyNotes": [
        "Always prefer relayed withdrawals (the default). Direct withdrawals (--direct) are NOT privacy-preserving: they publicly link your deposit address and withdrawal address onchain. Only use --direct if you understand and accept the privacy trade-off.",
        "ASP approval is required for both relayed and direct withdrawals. Declined deposits must ragequit publicly to the original deposit address.",
        "Relayed withdrawals must also respect the relayer minimum. If a withdrawal would leave a positive remainder below that minimum, the CLI warns so you can withdraw less, use --all/100%, or choose a public recovery path later."
      ],
      "supportsUnsigned": true,
      "supportsDryRun": true,
      "agentWorkflowNotes": [
        "If the CLI is interrupted after proof generation but before submission completes, re-run withdraw to generate a fresh proof and re-evaluate the current account state.",
        "If a direct or relayed withdrawal transaction was submitted but confirmation timed out, run sync --chain <chain> before retrying so local state can reconcile the onchain result."
      ]
    },
    "withdraw quote": {
      "command": "withdraw quote",
      "description": "Request relayer quote and limits without generating a proof",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "withdraw quote <amount> --asset <symbol|address>",
      "flags": [
        "--asset <symbol|address>",
        "--to <address>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "medium",
      "safeReadOnly": false,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools withdraw quote 0.1 ETH --to 0xRecipient...",
        "privacy-pools withdraw quote 100 USDC --agent --chain mainnet"
      ],
      "jsonFields": "{ mode: \"relayed-quote\", chain, asset, amount, recipient, minWithdrawAmount, minWithdrawAmountFormatted, baseFeeBPS, quoteFeeBPS, feeAmount, netAmount, feeCommitmentPresent, quoteExpiresAt, relayTxCost, extraGas?, extraGasFundAmount?, extraGasTxCost?, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "Quotes expire quickly; submit the withdrawal promptly after quoting if the fee is acceptable. Check runnable=false on nextActions for template commands that still need required user input.",
        "For agents, prefer `withdraw quote <amount> --asset <symbol|address>` or `withdraw quote <amount> <asset>`. The legacy asset-first positional form also works but is less clear for machine callers."
      ]
    },
    "ragequit": {
      "command": "ragequit",
      "description": "Publicly withdraw funds to your deposit address",
      "aliases": [
        "exit"
      ],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "ragequit [asset] --from-pa <PA-#>",
      "flags": [
        "--asset <symbol|address>",
        "--from-pa <PA-#>",
        "--unsigned [envelope|tx]",
        "--dry-run"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "fund_movement",
      "touchesFunds": true,
      "requiresHumanReview": true,
      "prerequisites": [
        "init (account state should be synced)"
      ],
      "examples": [
        "privacy-pools ragequit ETH --from-pa PA-1",
        "privacy-pools ragequit ETH --unsigned --from-pa PA-1",
        "privacy-pools ragequit ETH --dry-run --from-pa PA-1",
        "privacy-pools ragequit ETH --from-pa PA-1 --chain mainnet"
      ],
      "jsonFields": "{ operation, txHash, amount, asset, chain, poolAccountNumber, poolAccountId, poolAddress, scope, blockNumber, explorerUrl, destinationAddress?, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
      "jsonVariants": [
        "--unsigned: { mode, operation, chain, asset, amount, transactions[] }",
        "--unsigned tx: [{ from, to, data, value, valueHex, chainId, description }]",
        "--dry-run: { dryRun, operation, chain, asset, amount, destinationAddress?, poolAccountNumber, poolAccountId, selectedCommitmentLabel, selectedCommitmentValue, proofPublicSignals, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }"
      ],
      "safetyNotes": [
        "Ragequit is public and irreversible and reveals the original deposit address onchain."
      ],
      "supportsUnsigned": true,
      "supportsDryRun": true,
      "agentWorkflowNotes": [
        "If the public recovery transaction was submitted but confirmation timed out, re-run ragequit or sync --chain <chain> before retrying so the CLI can reconcile the onchain result."
      ]
    },
    "accounts": {
      "command": "accounts",
      "description": "List your Pool Accounts (individual deposit lineages) with balances",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "accounts",
      "flags": [
        "--no-sync",
        "--all-chains",
        "--details",
        "--summary",
        "--pending-only"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "local_state_write",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools accounts",
        "privacy-pools accounts --all-chains",
        "privacy-pools accounts --details",
        "privacy-pools accounts --summary",
        "privacy-pools accounts --chain <name> --pending-only",
        "privacy-pools accounts --agent",
        "privacy-pools accounts --no-sync --chain mainnet"
      ],
      "jsonFields": "{ chain, allChains?, chains?, warnings?, accounts: [{ poolAccountNumber, poolAccountId, status, aspStatus, asset, scope, value, hash, label, blockNumber, txHash, explorerUrl, chain?, chainId? }], balances: [{ asset, balance, usdValue, poolAccounts, chain?, chainId? }], pendingCount, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
      "jsonVariants": [
        "--summary: { chain, allChains?, chains?, warnings?, pendingCount, approvedCount, poiRequiredCount, declinedCount, unknownCount, spentCount, exitedCount, balances, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }",
        "--pending-only: { chain, allChains?, chains?, warnings?, accounts, pendingCount, nextActions?: [{ command, reason, when, cliCommand, args?, options?, runnable? }] }"
      ],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "Without --chain, accounts aggregates all CLI-supported mainnet chains by default. Use --all-chains to include testnets.",
        "Use --summary or --pending-only to reduce JSON size for polling loops.",
        "When a Pool Account disappears from --pending-only results, re-run accounts without --pending-only to confirm whether it was approved, declined, or requires Proof of Association (tornado.0xbow.io) before choosing withdraw or ragequit."
      ]
    },
    "migrate": {
      "command": "migrate",
      "description": "Inspect legacy migration readiness on CLI-supported chains",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "migrate",
      "flags": [
        "status [--all-chains]"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools migrate status",
        "privacy-pools migrate status --chain mainnet",
        "privacy-pools migrate status --all-chains --agent"
      ],
      "jsonFields": null,
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "migrate status": {
      "command": "migrate status",
      "description": "Show legacy migration readiness on CLI-supported chains",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "migrate status",
      "flags": [
        "--all-chains"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools migrate status",
        "privacy-pools migrate status --chain mainnet",
        "privacy-pools migrate status --all-chains --agent"
      ],
      "jsonFields": "{ mode: \"migration-status\", chain, allChains?, chains?, warnings?, status, requiresMigration, requiresWebsiteRecovery, isFullyMigrated, readinessResolved, submissionSupported: false, requiredChainIds, migratedChainIds, missingChainIds, websiteRecoveryChainIds, unresolvedChainIds, chainReadiness: [{ chain, chainId, status, candidateLegacyCommitments, expectedLegacyCommitments, migratedCommitments, legacyMasterSeedNullifiedCount, hasPostMigrationCommitments, isMigrated, legacySpendableCommitments, upgradedSpendableCommitments, declinedLegacyCommitments, reviewStatusComplete, requiresMigration, requiresWebsiteRecovery, scopes }] }",
      "jsonVariants": [],
      "safetyNotes": [
        "This command is read-only. It never submits migration transactions and does not persist rebuilt account state.",
        "When readinessResolved is false, treat the result as incomplete and review the account in the Privacy Pools website before acting on it.",
        "This check is limited to chains currently supported by the CLI. Review beta or other website-only migration surfaces in the Privacy Pools website."
      ],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "Use this after init/import when the CLI warns that a legacy pre-upgrade account may need website migration or website-based recovery."
      ]
    },
    "history": {
      "command": "history",
      "description": "Show chronological event history (deposits, migrations, withdrawals, ragequits)",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "history",
      "flags": [
        "--no-sync",
        "--limit <n>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "local_state_write",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools history",
        "privacy-pools history --limit 10",
        "privacy-pools history --agent",
        "privacy-pools history --no-sync --chain mainnet"
      ],
      "jsonFields": "{ chain, events: [{ type, asset, poolAddress, poolAccountNumber, poolAccountId, value, blockNumber, txHash, explorerUrl }] }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    },
    "sync": {
      "command": "sync",
      "description": "Force-sync local account state from onchain events",
      "aliases": [],
      "execution": {
        "owner": "js-runtime",
        "nativeModes": [
          "help"
        ]
      },
      "usage": "sync",
      "flags": [
        "-a, --asset <symbol|address>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": true,
      "expectedLatencyClass": "slow",
      "safeReadOnly": false,
      "sideEffectClass": "local_state_write",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [
        "init"
      ],
      "examples": [
        "privacy-pools sync",
        "privacy-pools sync --asset ETH --agent",
        "privacy-pools sync --chain mainnet"
      ],
      "jsonFields": "{ chain, syncedPools, availablePoolAccounts, syncedSymbols?, previousAvailablePoolAccounts? }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": [
        "Use sync after deposit, withdraw, or ragequit confirmation timeouts before retrying. It rebuilds local account state from onchain events and prevents duplicate recovery attempts against already-confirmed transactions."
      ]
    },
    "completion": {
      "command": "completion",
      "description": "Generate shell completion script",
      "aliases": [],
      "execution": {
        "owner": "native-shell",
        "nativeModes": [
          "default",
          "help"
        ]
      },
      "usage": "completion",
      "flags": [
        "[shell]",
        "--shell <shell>"
      ],
      "globalFlags": [
        "-c, --chain <name>",
        "-j, --json",
        "--format <format>",
        "-y, --yes",
        "-r, --rpc-url <url>",
        "--agent",
        "-q, --quiet",
        "--no-banner",
        "-v, --verbose",
        "--timeout <seconds>",
        "--no-color"
      ],
      "requiresInit": false,
      "expectedLatencyClass": "fast",
      "safeReadOnly": true,
      "sideEffectClass": "read_only",
      "touchesFunds": false,
      "requiresHumanReview": false,
      "prerequisites": [],
      "examples": [
        "privacy-pools completion zsh > ~/.zsh/completions/_privacy-pools",
        "privacy-pools completion bash > ~/.local/share/bash-completion/completions/privacy-pools",
        "privacy-pools completion fish > ~/.config/fish/completions/privacy-pools.fish",
        "privacy-pools completion powershell >> $PROFILE"
      ],
      "jsonFields": "{ mode, shell, completionScript }",
      "jsonVariants": [],
      "safetyNotes": [],
      "supportsUnsigned": false,
      "supportsDryRun": false,
      "agentWorkflowNotes": []
    }
  },
  "executionRoutes": {
    "init": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "upgrade": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "flow": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "flow start": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "flow watch": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "flow status": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "flow ragequit": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "pools": {
      "owner": "hybrid",
      "nativeModes": [
        "default-list",
        "csv-list",
        "structured-list",
        "help"
      ]
    },
    "activity": {
      "owner": "hybrid",
      "nativeModes": [
        "default",
        "csv",
        "structured",
        "help"
      ]
    },
    "stats": {
      "owner": "hybrid",
      "nativeModes": [
        "default",
        "csv",
        "structured-default",
        "structured-global",
        "help"
      ]
    },
    "stats global": {
      "owner": "hybrid",
      "nativeModes": [
        "default",
        "csv",
        "structured",
        "help"
      ]
    },
    "stats pool": {
      "owner": "hybrid",
      "nativeModes": [
        "default",
        "csv",
        "structured",
        "help"
      ]
    },
    "status": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "capabilities": {
      "owner": "native-shell",
      "nativeModes": [
        "default",
        "help"
      ]
    },
    "describe": {
      "owner": "native-shell",
      "nativeModes": [
        "default",
        "help"
      ]
    },
    "guide": {
      "owner": "native-shell",
      "nativeModes": [
        "default",
        "help"
      ]
    },
    "deposit": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "withdraw": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "withdraw quote": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "ragequit": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "accounts": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "migrate": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "migrate status": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "history": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "sync": {
      "owner": "js-runtime",
      "nativeModes": [
        "help"
      ]
    },
    "completion": {
      "owner": "native-shell",
      "nativeModes": [
        "default",
        "help"
      ]
    }
  },
  "globalFlags": [
    {
      "flag": "-c, --chain <name>",
      "description": "Target chain (mainnet, arbitrum, optimism, ...)"
    },
    {
      "flag": "-j, --json",
      "description": "Machine-readable JSON output on stdout"
    },
    {
      "flag": "--format <format>",
      "description": "Output format: table (default), csv, json"
    },
    {
      "flag": "-y, --yes",
      "description": "Skip confirmation prompts"
    },
    {
      "flag": "-r, --rpc-url <url>",
      "description": "Override RPC URL"
    },
    {
      "flag": "--agent",
      "description": "Machine-friendly mode (alias for --json --yes --quiet)"
    },
    {
      "flag": "-q, --quiet",
      "description": "Suppress human-oriented stderr output"
    },
    {
      "flag": "--no-banner",
      "description": "Disable ASCII banner output"
    },
    {
      "flag": "-v, --verbose",
      "description": "Enable verbose/debug output"
    },
    {
      "flag": "--timeout <seconds>",
      "description": "Network/transaction timeout in seconds (default: 30)"
    },
    {
      "flag": "--no-color",
      "description": "Disable colored output (also respects NO_COLOR env var)"
    }
  ],
  "agentWorkflow": [
    "1. privacy-pools status --agent",
    "2. privacy-pools init --agent --default-chain <chain> --show-mnemonic",
    "3. privacy-pools pools --agent --chain <chain>",
    "4. privacy-pools flow start <amount> <asset> --to <address> --agent --chain <chain>",
    "5. privacy-pools flow watch [workflowId|latest] --agent",
    "6. privacy-pools flow ragequit [workflowId|latest] --agent  (optional public recovery after the deposit exists; canonical if the saved workflow is declined)",
    "7. privacy-pools deposit <amount> --asset <symbol> --agent --chain <chain>  (manual alternative)",
    "8. privacy-pools accounts --agent --chain <chain> --pending-only  (reviewed entries disappear; confirm approved vs declined vs poi_required with accounts --agent --chain <chain>)",
    "9. privacy-pools withdraw <amount> --asset <symbol> --to <address> --agent --chain <chain>"
  ],
  "agentNotes": {
    "polling": "After depositing, poll 'accounts --agent --chain <chain> --pending-only' while the Pool Account remains pending. Reviewed entries disappear from --pending-only results; once gone, re-run 'accounts --agent --chain <chain>' to confirm whether aspStatus is 'approved', 'declined', or 'poi_required'. Withdraw only after approval; ragequit if declined; complete Proof of Association at tornado.0xbow.io first if poi_required. Always preserve the same --chain scope for both polling and confirmation. Most deposits are approved within 1 hour, but some may take longer (up to 7 days). Follow nextActions from the deposit response for the canonical polling command.",
    "withdrawQuote": "Use 'withdraw quote <amount> --asset <symbol> --agent' to check relayer fees before committing to a withdrawal.",
    "firstRun": "Proof generation uses bundled checksum-verified circuit artifacts shipped with the CLI. The first proof may spend a moment verifying them; subsequent proofs are typically ~10-30s.",
    "unsignedMode": "--unsigned builds transaction payloads without signing or submitting. Use --unsigned tx for a raw transaction array (no envelope). Requires init (recovery phrase) for deposit secret generation, but does NOT require a signer key. The 'from' field is included for signer-aware workflows: it is null when the signer is unconstrained, and set to the required caller address when the protocol requires one.",
    "metaFlag": "--agent is equivalent to --json --yes --quiet. Use it to suppress all stderr output and skip prompts.",
    "statusCheck": "Run 'status --agent' before transacting. Use recommendedMode plus blockingIssues[]/warnings[] for machine gating, and keep readyForDeposit/readyForWithdraw/readyForUnsigned as configuration capability flags only. Those flags confirm the wallet is set up, NOT that withdrawable funds exist. Check 'accounts --agent --chain <chain>' to verify fund availability before withdrawing on a specific chain. Use bare 'accounts --agent' only for the default multi-chain mainnet dashboard. When recommendedMode is read-only because RPC or ASP health is degraded, follow status nextActions back to public discovery and avoid account-state guidance until connectivity is restored. If only the ASP is down while RPC stays healthy, public recovery still remains available through ragequit, flow ragequit, or unsigned ragequit payloads when the affected account or workflow is already known."
  },
  "schemas": {
    "aspApprovalStatus": {
      "values": [
        "approved",
        "pending",
        "poi_required",
        "declined",
        "unknown"
      ],
      "description": "ASP approval status for a Pool Account. 'approved' means the deposit has been vetted and is eligible for private withdrawal. 'pending' means the ASP has not yet approved the deposit. 'poi_required' means Proof of Association (tornado.0xbow.io) is required before private withdrawal. 'declined' means the ASP rejected the deposit for private withdrawal. 'unknown' applies to exited or spent accounts, or when ASP status could not be determined."
    },
    "poolAccountStatus": {
      "values": [
        "approved",
        "pending",
        "poi_required",
        "declined",
        "unknown",
        "spent",
        "exited"
      ],
      "description": "User-facing status of a Pool Account. Active accounts surface their effective review state ('approved', 'pending', 'poi_required', 'declined', or 'unknown'). 'spent' means an approved account was withdrawn. 'exited' means ragequit/exit was used."
    },
    "errorCategories": {
      "values": [
        "INPUT",
        "RPC",
        "ASP",
        "RELAYER",
        "PROOF",
        "CONTRACT",
        "UNKNOWN"
      ],
      "exitCodes": {
        "INPUT": 2,
        "RPC": 3,
        "ASP": 4,
        "RELAYER": 5,
        "PROOF": 6,
        "CONTRACT": 7,
        "UNKNOWN": 1
      },
      "description": "Error responses include top-level errorCode/errorMessage plus error.{ code, category, message, hint?, retryable? }."
    },
    "unsignedOutput": {
      "envelopeFormat": "{ schemaVersion, success, mode, operation, chain, transactions: [{ from, to, data, value, ... }], ... }",
      "txFormat": "[{ from, to, data, value, valueHex, chainId, description }]: raw array, no envelope wrapper. Intended for direct piping to signing tools.",
      "note": "Default --unsigned emits the envelope format. Use --unsigned tx for raw transaction array only."
    },
    "nextActions": {
      "shape": "{ command, reason, when, args?: string[], options?: Record<string, string|number|boolean|null>, runnable?: boolean }",
      "description": "Canonical workflow guidance for agents. Follow these command suggestions instead of parsing natural-language output. Current nextActions are emitted only when the CLI has a low-ambiguity follow-up to recommend. When runnable is omitted or true, the command is fully specified and can be executed as shown. When runnable is false, the action is a template and requires additional user input before execution."
    },
    "sideEffectClass": {
      "values": [
        "read_only",
        "local_state_write",
        "network_write",
        "fund_movement"
      ],
      "description": "Machine-readable risk classification for a command path. read_only never mutates local or remote protocol state. local_state_write may mutate local CLI state or secrets. network_write is reserved for remote mutations that do not directly move user funds. fund_movement may submit deposits, withdrawals, or public recoveries."
    },
    "statusRecommendedMode": {
      "values": [
        "setup-required",
        "read-only",
        "unsigned-only",
        "ready"
      ],
      "description": "High-level preflight recommendation derived from the current wallet/configuration state. setup-required means init or recovery setup is incomplete. unsigned-only means read-only and unsigned transaction building are safe but a valid signer is unavailable. ready means the wallet is configured for deposits and withdrawals. read-only means status detected degraded RPC or ASP health, so public discovery is the default safe path until connectivity is restored. When only the ASP is degraded but RPC remains healthy, public recovery may still be available if the affected account or workflow is already known."
    },
    "statusIssues": {
      "blockingIssueShape": "{ code, message, affects: (\"deposit\"|\"withdraw\"|\"unsigned\"|\"discovery\")[] }",
      "warningShape": "{ code, message, affects: (\"deposit\"|\"withdraw\"|\"unsigned\"|\"discovery\")[] }",
      "description": "Structured preflight issues returned by status --agent. blockingIssues describe setup blockers that should stop execution. warnings describe degraded or follow-up-worthy states that may still allow safe read-only usage."
    }
  },
  "supportedChains": [
    {
      "name": "mainnet",
      "chainId": 1,
      "testnet": false
    },
    {
      "name": "arbitrum",
      "chainId": 42161,
      "testnet": false
    },
    {
      "name": "optimism",
      "chainId": 10,
      "testnet": false
    },
    {
      "name": "sepolia",
      "chainId": 11155111,
      "testnet": true
    },
    {
      "name": "op-sepolia",
      "chainId": 11155420,
      "testnet": true
    }
  ],
  "protocol": {
    "family": "privacy-pools",
    "generation": "v1",
    "profile": "privacy-pools-v1",
    "displayName": "Privacy Pools v1",
    "coreSdkPackage": "@0xbow/privacy-pools-core-sdk",
    "coreSdkVersion": "1.2.0",
    "supportedChainPolicy": "cli-curated",
    "notes": [
      "Chain support is a CLI-curated subset of the broader website deployment catalog.",
      "Proof, signer, mnemonic, workflow, migration, relayer, and transaction-composition logic stays in JS."
    ]
  },
  "runtime": {
    "cliVersion": "1.7.0",
    "jsonSchemaVersion": "1.7.0",
    "accountFileVersion": 3,
    "workflowSnapshotVersion": "2",
    "workflowSecretVersion": "1",
    "runtimeVersion": "v1",
    "workerProtocolVersion": "1",
    "manifestVersion": "1",
    "nativeBridgeVersion": "1"
  },
  "safeReadOnlyCommands": [
    "flow",
    "flow status",
    "pools",
    "activity",
    "stats",
    "stats global",
    "stats pool",
    "status",
    "capabilities",
    "describe",
    "guide",
    "migrate",
    "migrate status",
    "completion"
  ],
  "jsonOutputContract": "All commands emit { schemaVersion, success, ...payload } on stdout when --json or --agent is set. Errors emit { schemaVersion, success: false, errorCode, errorMessage, error: { code, category, message, hint?, retryable? } }. Exception: --unsigned tx emits a raw transaction array without the envelope.",
  "documentation": {
    "reference": "docs/reference.md",
    "agentGuide": "AGENTS.md",
    "changelog": "CHANGELOG.md",
    "runtimeUpgrades": "docs/runtime-upgrades.md",
    "jsonContract": "docs/contracts/cli-json-contract.v1.7.0.json"
  }
};

export const GENERATED_COMMAND_MANIFEST = {
  manifestVersion: "1",
  runtimeVersion: "v1",
  commandPaths: GENERATED_COMMAND_PATHS,
  rootCommands: GENERATED_ROOT_COMMANDS,
  staticLocalCommands: GENERATED_STATIC_LOCAL_COMMANDS,
  aliasMap: GENERATED_COMMAND_ALIAS_MAP,
  commandRoutes: GENERATED_COMMAND_ROUTES,
  capabilitiesPayload: GENERATED_CAPABILITIES_PAYLOAD,
} as const;
